#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponNockGun

#include "Basic.hpp"

#include "BP_WeaponRangedBase_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WeaponNockGun.BP_WeaponNockGun_C
// 0x0010 (0x04D0 - 0x04C0)
class ABP_WeaponNockGun_C final : public ABP_WeaponRangedBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponNockGun_C;                 // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          ApplyDaze;                                         // 0x04C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C9[0x3];                                      // 0x04C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DefaultKnockback;                                  // 0x04CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_WeaponNockGun(int32 EntryPoint);
	void PrimaryFire(const struct FVector& CameraLocation_0, const struct FVector& Direction_0, bool FullPrecision_0, bool WasSprinting_0);
	void ReceiveBeginPlay();
	void SecondaryFire(const struct FVector& CameraLocation_0, const struct FVector& Direction_0);
	void SecundaryFired();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponNockGun_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponNockGun_C")
	}
	static class ABP_WeaponNockGun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponNockGun_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponNockGun_C;

SDK_NAMESPACE_END
