#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponDragonPistol

#include "Basic.hpp"

#include "BP_WeaponRangedBase_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WeaponDragonPistol.BP_WeaponDragonPistol_C
// 0x0010 (0x04D0 - 0x04C0)
class ABP_WeaponDragonPistol_C final : public ABP_WeaponRangedBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponDragonPistol_C;            // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Bullet;                                            // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_WeaponDragonPistol(int32 EntryPoint);
	void HolsteredEvent();
	void ReloadEvent(class ABP_Character_C* CharacterRef_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponDragonPistol_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponDragonPistol_C")
	}
	static class ABP_WeaponDragonPistol_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponDragonPistol_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponDragonPistol_C;

SDK_NAMESPACE_END
