#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponDualFlintlock

#include "Basic.hpp"

#include "BP_WeaponRangedBase_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WeaponDualFlintlock.BP_WeaponDualFlintlock_C
// 0x0010 (0x04D0 - 0x04C0)
class ABP_WeaponDualFlintlock_C final : public ABP_WeaponRangedBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponDualFlintlock_C;           // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         SecondaryFireAmount;                               // 0x04C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_WeaponDualFlintlock(int32 EntryPoint);
	void SecondaryFire(const struct FVector& CameraLocation_0, const struct FVector& Direction_0);
	void HolsteredEvent();
	void ReloadEvent(class ABP_Character_C* CharacterRef_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponDualFlintlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponDualFlintlock_C")
	}
	static class ABP_WeaponDualFlintlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponDualFlintlock_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponDualFlintlock_C;

SDK_NAMESPACE_END
