#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponMultiCrossbow

#include "Basic.hpp"

#include "BP_WeaponRangedBase_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WeaponMultiCrossbow.BP_WeaponMultiCrossbow_C
// 0x0010 (0x04D0 - 0x04C0)
class ABP_WeaponMultiCrossbow_C final : public ABP_WeaponRangedBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponMultiCrossbow_C;           // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_WeaponMultiCrossbow(int32 EntryPoint);
	void LoadedState(bool Loaded);
	void PrimaryFire(const struct FVector& CameraLocation_0, const struct FVector& Direction_0, bool FullPrecision_0, bool WasSprinting_0);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponMultiCrossbow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponMultiCrossbow_C")
	}
	static class ABP_WeaponMultiCrossbow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponMultiCrossbow_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponMultiCrossbow_C;

SDK_NAMESPACE_END
