#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wind

#include "Basic.hpp"

#include "BP_Wind_classes.hpp"
#include "BP_Wind_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Wind.BP_Wind_C.ExecuteUbergraph_BP_Wind
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Wind_C::ExecuteUbergraph_BP_Wind(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Wind_C", "ExecuteUbergraph_BP_Wind");

	Params::BP_Wind_C_ExecuteUbergraph_BP_Wind Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Wind.BP_Wind_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Wind_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Wind_C", "ReceiveTick");

	Params::BP_Wind_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Wind.BP_Wind_C.OnRep_NewRotation
// (BlueprintCallable, BlueprintEvent)

void ABP_Wind_C::OnRep_NewRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Wind_C", "OnRep_NewRotation");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
