#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponTomahawk

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_WeaponMeleeBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WeaponTomahawk.BP_WeaponTomahawk_C
// 0x0010 (0x0480 - 0x0470)
class ABP_WeaponTomahawk_C final : public ABP_WeaponMeleeBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponTomahawk_C;                // 0x0470(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Ready;                                             // 0x0478(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShowWeapon;                                        // 0x0479(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void ExecuteUbergraph_BP_WeaponTomahawk(int32 EntryPoint);
	void SecondaryFire(const struct FVector& CameraLocation_0, const struct FVector& Direction_0);
	void MC_Throw(const struct FVector& Location, const struct FVector& Direction_0, int32 TeamID);
	void OnRep_ShowWeapon();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponTomahawk_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponTomahawk_C")
	}
	static class ABP_WeaponTomahawk_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponTomahawk_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponTomahawk_C;

SDK_NAMESPACE_END
