#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponRepeater

#include "Basic.hpp"

#include "BP_WeaponRangedBase_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_WeaponRepeater.BP_WeaponRepeater_C
// 0x0020 (0x04E0 - 0x04C0)
class ABP_WeaponRepeater_C final : public ABP_WeaponRangedBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponRepeater_C;                // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Bullet;                                            // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentClip;                                       // 0x04D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_WeaponRepeater(int32 EntryPoint);
	void PrimaryFire(const struct FVector& CameraLocation_0, const struct FVector& Direction_0, bool FullPrecision_0, bool WasSprinting_0);
	void VisualClipAmountEvent();
	void ReloadEvent(class ABP_Character_C* CharacterRef_0);
	void ReceiveTick(float DeltaSeconds);
	void SwapMeshBasedOnClipAmount(int32 ClipAmount_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponRepeater_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponRepeater_C")
	}
	static class ABP_WeaponRepeater_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponRepeater_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponRepeater_C;

SDK_NAMESPACE_END
