#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_CannonAmmo

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_CannonAmmo.E_CannonAmmo
// NumValues: 0x0008
enum class E_CannonAmmo : uint8
{
	NewEnumerator2                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator6                           = 5,
	NewEnumerator7                           = 6,
	E_MAX                                    = 7,
};

SDK_NAMESPACE_END
