#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_CharacterVisibility

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_CharacterVisibility.E_CharacterVisibility
// NumValues: 0x0004
enum class E_CharacterVisibility : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	E_MAX                                    = 3,
};

SDK_NAMESPACE_END
