#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_Party_Member_Ship

#include "Basic.hpp"

#include "EOS_Party_Member_Ship_classes.hpp"
#include "EOS_Party_Member_Ship_parameters.hpp"


SDK_NAMESPACE_START

// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.ExecuteUbergraph_EOS_Party_Member_Ship
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Party_Member_Ship_C::ExecuteUbergraph_EOS_Party_Member_Ship(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "ExecuteUbergraph_EOS_Party_Member_Ship");

	Params::EOS_Party_Member_Ship_C_ExecuteUbergraph_EOS_Party_Member_Ship Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Ship Cosmetics Updated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ShipCustomisations_renamed&Ship_Cosmetics                                         (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEOS_Party_Member_Ship_C::Ship_Cosmetics_Updated(const struct FST_ShipCustomisations_renamed& Ship_Cosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Ship Cosmetics Updated");

	Params::EOS_Party_Member_Ship_C_Ship_Cosmetics_Updated Parms{};

	Parms.Ship_Cosmetics = std::move(Ship_Cosmetics);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Initialize
// (BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Bind To EOS Events
// (BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Bind_To_EOS_Events()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Bind To EOS Events");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEOS_Party_Member_Ship_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Update Ship Cosmetics
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ShipCustomisations_renamed&Cached_Cosmetics_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEOS_Party_Member_Ship_C::Update_Ship_Cosmetics(const struct FST_ShipCustomisations_renamed& Cached_Cosmetics_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Update Ship Cosmetics");

	Params::EOS_Party_Member_Ship_C_Update_Ship_Cosmetics Parms{};

	Parms.Cached_Cosmetics_0 = std::move(Cached_Cosmetics_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Reevaluate This Member
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Reevaluate_This_Member()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Reevaluate This Member");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Check If Mine
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Check_If_Mine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Check If Mine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Finished Loading
// (Public, BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Finished_Loading()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Finished Loading");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Update Ship
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ShipCustomisations_renamed&Ship_Cosmetics                                         (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void AEOS_Party_Member_Ship_C::Update_Ship(const struct FST_ShipCustomisations_renamed& Ship_Cosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Update Ship");

	Params::EOS_Party_Member_Ship_C_Update_Ship Parms{};

	Parms.Ship_Cosmetics = std::move(Ship_Cosmetics);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Manually Update Data
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Manually_Update_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Manually Update Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Party_Member_Ship.EOS_Party_Member_Ship_C.Update Ship Reference on Controller
// (Public, BlueprintCallable, BlueprintEvent)

void AEOS_Party_Member_Ship_C::Update_Ship_Reference_on_Controller()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Party_Member_Ship_C", "Update Ship Reference on Controller");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
