#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_VoiceChannel_Referemce

#include "Basic.hpp"

#include "EOS_VoiceChannel_Referemce_classes.hpp"
#include "EOS_VoiceChannel_Referemce_parameters.hpp"


SDK_NAMESPACE_START

// Function EOS_VoiceChannel_Referemce.EOS_VoiceChannel_Referemce_C.ToString
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString*                          Value                                                  (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UEOS_VoiceChannel_Referemce_C::ToString(class FString* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_VoiceChannel_Referemce_C", "ToString");

	Params::EOS_VoiceChannel_Referemce_C_ToString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = std::move(Parms.Value);
}


SDK_NAMESPACE_END
