#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_Party_Member_Position

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EOS_Party_Member_Position.EOS_Party_Member_Position_C
// 0x0058 (0x0278 - 0x0220)
class AEOS_Party_Member_Position_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FTransform>                     Party_Member_Spawn_Transforms;                     // 0x0230(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class ABP_Mannequin_C*>                Party_Member_Spawn_Mannequins;                     // 0x0240(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	TArray<struct FTransform>                     Party_Ship_Spawn_Transforms;                       // 0x0250(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class ABP_BoatMeshBase_C*>             Party_Ship_Spawn_Mannequins;                       // 0x0260(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	bool                                          Initial_Reevaluation;                              // 0x0270(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Generate_Spawn_Transforms();
	void Left_Party(bool Successful);
	void Reevaluate_Members();
	void Bind_To_EOS_Events();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_EOS_Party_Member_Position(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EOS_Party_Member_Position_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EOS_Party_Member_Position_C")
	}
	static class AEOS_Party_Member_Position_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEOS_Party_Member_Position_C>();
	}
};
DUMPER7_ASSERTS_AEOS_Party_Member_Position_C;

SDK_NAMESPACE_END
