#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_GameInstance

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "OnlineSubsystemBlueprints_structs.hpp"
#include "E_Platforms_structs.hpp"
#include "ST_InventoryTrackingItem_renamed_structs.hpp"
#include "E_GameModes_structs.hpp"
#include "VaRest_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EOS_GameInstance.EOS_GameInstance_C
// 0x06A8 (0x0850 - 0x01A8)
class UEOS_GameInstance_C : public UGameInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Initialized_EOS_Instance;                          // 0x01B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Cached_Primary_Platform_ID;                        // 0x01B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   Joined_Session_Name;                               // 0x01C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool Successful, class UTexture* Avatar, const struct FUniqueNetIdRepl& User_ID)> EOS_Friend_Get_Avatar; // 0x01D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful, const class FString& Error_Message)> EOS_Auth_Logged_In; // 0x01E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UEOS_FriendReference_C*>         EOS_Friends;                                       // 0x01F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void(bool Successful, TArray<class UEOS_FriendReference_C*>& Friends)> EOS_Friend_Fetched_Friends; // 0x0200(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TSet<class FString>                           Session_Follow_Consumed_Ids;                       // 0x0210(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void()>              EOS_Party_On_Invites_Changed;                      // 0x0260(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class FName Session_Name)> EOS_Party_On_Party_Leader_Was_Followed_to_Session; // 0x0270(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful)> EOS_Party_On_Party_Created;                      // 0x0280(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful)> EOS_Party_On_Friend_Invited;                     // 0x0290(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful)> EOS_Party_On_Joined_Party;                       // 0x02A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FUniqueNetIdRepl& Member_Id)> EOS_Party_On_Joined_Member; // 0x02B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful)> EOS_Party_On_Kicked_Member;                      // 0x02C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful)> EOS_Party_On_Left_Party;                         // 0x02D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UEOS_SessionReference_C*>        Search_Results;                                    // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UOnlineSessionSearch*                   Online_Search;                                     // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool Successful)> CreatedSession;                                  // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful, TArray<class UEOS_SessionReference_C*>& Search_Results_0)> FoundSessions; // 0x0308(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Successful, class UEOS_SessionReference_C* Session)> JoinedSession; // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FUniqueNetIdRepl                       Hosting_Player_Id;                                 // 0x0328(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 Cached_Auth_Platform_ID;                           // 0x0350(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TMap<class FName, struct FOnlineSessionSettingBP> Server_Settings;                               // 0x0360(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UEOS_PartyReference_C*                  Primary_Party;                                     // 0x03B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UReadablePartyData* Party_Data)> EOS_Party_On_Party_Data_Received; // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FUniqueNetIdRepl& Member_Id, class UReadablePartyData* Party_Member_Data)> EOS_Party_On_Party_Member_Data_Received; // 0x03C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FUniqueNetIdRepl& MemberId, EMemberExitedReason_ Reason, class UEOS_PartyMemberReference_C* Party_Member)> EOS_Party_On_Party_Member_Leaving; // 0x03D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMap<struct FUniqueNetIdRepl, class UTexture*> EOS_Friends_Avatars;                              // 0x03E8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void(class UEOS_FriendReference_C* Updated_Friend)> EOS_Friend_Change;  // 0x0438(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UEOS_FriendReference_C* Friend, const struct FOnlineUserPresenceData& Presence)> EOS_Friend_Presence_Change; // 0x0448(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          ForceDisableMM;                                    // 0x0458(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Enable_Match_Making;                               // 0x0459(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45A[0x6];                                      // 0x045A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Current_EOS_Auth_Step;                             // 0x0460(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          CanLinkAccount;                                    // 0x0478(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CachedFriendsList;                                 // 0x0479(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47A[0x6];                                      // 0x047A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              Fetched_Global_Config;                             // 0x0480(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FUniqueNetIdRepl& User_ID, const struct FOnlineUserPresenceData& Presence_Data, bool Successful)> Received_Presence; // 0x0490(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FString                                 Server_Name;                                       // 0x04A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Has_Session;                                       // 0x04B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B1[0x7];                                      // 0x04B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Session_Id;                                        // 0x04B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UEOS_Party_Replicated_Attribute_C*      Matchmaking_Active_Sync;                           // 0x04C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool Success, const class FString& party_id)> Joined_Match_Making_Queue; // 0x04D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FString                                 Matchmaking_Party_ID;                              // 0x04E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         Math_Maker_Ping_Frequency;                         // 0x04F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Found_Matchmaking_Session;                         // 0x04F4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F5[0x3];                                      // 0x04F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Target_Matchmaking_Session_ID;                     // 0x04F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   Target_Matchmaking_Session_Name;                   // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Last_Stop_Matchmaking_Reason;                      // 0x0510(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(bool Success, bool Found_Match, const class FString& Left_Reason, bool Aborted)> Left_Match_Making_Queue; // 0x0520(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          MatchMakingCallInProgress;                         // 0x0530(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_531[0x7];                                      // 0x0531(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool Success)>  DestroyedSession;                                  // 0x0538(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         Matchmaking_Desired_Team_Id;                       // 0x0548(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54C[0x4];                                      // 0x054C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 UserName;                                          // 0x0550(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	E_Platforms                                   CachedPrimaryPlatform;                             // 0x0560(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Party_Is_Matchmaking;                              // 0x0561(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsReady;                                           // 0x0562(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_563[0x5];                                      // 0x0563(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Matchmaking_Status;                                // 0x0568(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	E_Platforms                                   CachedAuthPlatform;                                // 0x0578(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Needs_Update;                                      // 0x0579(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Has_Dev_Version;                                   // 0x057A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_57B[0x1];                                      // 0x057B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Players_In_Matchmaking_Queue;                      // 0x057C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HasFetchedInventory;                               // 0x0580(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_581[0x7];                                      // 0x0581(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FST_InventoryTrackingItem_renamed> Inventory;                                      // 0x0588(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          HasFetchedEpicDLC;                                 // 0x0598(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Is_Developer;                                      // 0x0599(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Is_Moderator;                                      // 0x059A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59B[0x5];                                      // 0x059B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UEvents_Manager_C*                      Events_Manager;                                    // 0x05A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsJoiningParty;                                    // 0x05A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          JoinMatchMakingCallInProgress;                     // 0x05A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5AA[0x6];                                      // 0x05AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         Developer_List;                                    // 0x05B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         Max_Party_Members;                                 // 0x05C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Party_Locked;                                      // 0x05C4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5C5[0x3];                                      // 0x05C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Queue_number;                                      // 0x05C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5CC[0x4];                                      // 0x05CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<struct FUniqueNetIdRepl, class UEOS_PartyMemberReference_C*> Party_Members;                 // 0x05D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USG_EOS_Session_Save_C*                 Saved_Session;                                     // 0x0620(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         Moderator_List;                                    // 0x0628(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Has_Saved_Session;                                 // 0x0638(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_639[0x7];                                      // 0x0639(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              EOS_Party_On_Party_Size_Changed;                   // 0x0640(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UEOS_Party_Replicated_Attribute_C*      Party_Locked_Sync;                                 // 0x0650(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEOS_Party_Replicated_Attribute_C*      Party_Session_Follow_Sync;                         // 0x0658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEOS_PartyMemberReference_C*            Personal_Party_Member_Reference;                   // 0x0660(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         Muted_List;                                        // 0x0668(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FString>                         Restricted_List;                                   // 0x0678(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Is_Initializing_EOS_Instance;                      // 0x0688(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_689[0x7];                                      // 0x0689(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              EOS_Initialized;                                   // 0x0690(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FString                                 Restrict_Key;                                      // 0x06A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UBlueprintWebSocket*                    Game_Services_WebSocket;                           // 0x06B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              WS_Game_Services_Connected;                        // 0x06B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const class FString& Error)> WS_Game_Services_Connection_Error;    // 0x06C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const class FString& Message)> WS_Game_Services_Message_Received;  // 0x06D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const class FString& Message)> WS_Game_Services_Message_Sent;      // 0x06E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UEOS_SessionReference_C*                Joined_Session;                                    // 0x06F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Server_Notification;                               // 0x0700(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 CachedSteamID;                                     // 0x0710(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 CachedEpicID;                                      // 0x0720(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         Version;                                           // 0x0730(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_734[0x4];                                      // 0x0734(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Last_Session_ID;                                   // 0x0738(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Clean_Leave;                                       // 0x0748(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_749[0x3];                                      // 0x0749(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Queue_length;                                      // 0x074C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              Pinged_Match_Making_Queue;                         // 0x0750(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool Success, const class FString& Reason)> Attempting_To_Join_Session_From_String; // 0x0760(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UEOS_PartyJoinRequestReference_C*> Discord_Join_Request;                            // 0x0770(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UEOS_PartyInviteReference_C*>    Discord_Invites;                                   // 0x0780(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<struct FUniqueNetIdRepl, class UTexture*> EOS_Friends_Avatar_Queue;                         // 0x0790(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsFetchingAvatar;                                  // 0x07E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7E1[0x7];                                      // 0x07E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       Finding_Avatar_Unique_Net_ID;                      // 0x07E8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          BattleRoyale_Enabled;                              // 0x0810(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Conquest_Enabled;                                  // 0x0811(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Gun_Game_Enabled;                                  // 0x0812(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          BattleRoyale_Junior_Enabled;                       // 0x0813(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_814[0x4];                                      // 0x0814(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UEOS_Party_Replicated_Attribute_C*      Matchmaking_State_Sync;                            // 0x0818(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEOS_Party_Replicated_Attribute_C*      Matchmaking_Team_ID_Sync;                          // 0x0820(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEOS_Party_Replicated_Attribute_C*      Matchmaking_Ping_Sync;                             // 0x0828(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEOS_Party_Replicated_Attribute_C*      Matchmaking_Progress_Sync;                         // 0x0830(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           Matchmaking_Stop_Fallback_Timer;                   // 0x0838(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           Matchmaking_Ping_Handler;                          // 0x0840(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          JoinAsSpectator;                                   // 0x0848(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          RiseOfTheUndeadFleet_Enabled;                      // 0x0849(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_EOS_GameInstance(int32 EntryPoint);
	void Initialize_EOS();
	void OnSignedInComplete(int32 LocalUserNum, bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Error);
	void EOS_Initialize_Auth_Events();
	void EOS_Start_Login(int32 Local_User_Num);
	void Fetch_Next_Avatar();
	void Fetch_Avatar_Smart(const struct FUniqueNetIdRepl& Unique_Net_Id, class UTexture* Default_Avatar);
	void Presence_Event_Received(const struct FUniqueNetIdRepl& UserId, const struct FOnlineUserPresenceData& Presence);
	void EOS_Initialize_Friend_Events();
	void EOS_Friend_Changed(int32 Friend_number);
	void Fetch_Avatar_Friend(class UEOS_FriendReference_C* Friend, class UTexture* Default_Avatar);
	void Fetch_Avatar(const struct FUniqueNetIdRepl& User_ID, class UTexture* Default_Avatar);
	void EOS_Read_And_Get_Friends();
	void Call_Party_Size_Changed_Delayed();
	void Join_Party_From_Party_Join_Object(class UOnlinePartyJoinInfo* Target);
	void Join_Party_From_ID(const class FString& LobbyId);
	void Got_Kicked(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId);
	void Joined_Party(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId);
	void Party_Member_Left(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& MemberId, EMemberExitedReason_ Reason);
	void Party_Member_Joined(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& MemberId);
	void Send_Party_Member_Data(const class FString& Attribute_Name, const struct FVariantDataBP& Data);
	void Send_Party_Data(const class FString& Attribute_Name, const struct FVariantDataBP& Data);
	void Reject_Invitation(class UEOS_PartyInviteReference_C* Rejected_Invite);
	void Party_Data_Received(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, class FName Namespace, class UReadablePartyData* PartyData);
	void Party_Member_Data_Receieved(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& MemberId, class FName Namespace, class UReadablePartyData* PartyData);
	void Leave_Party();
	void Kick_Member(const struct FUniqueNetIdRepl& Party_Member_Id);
	void Join_Party_From_Invite(class UEOS_PartyInviteReference_C* Invite);
	void Invite_Friend_To_Party(class UEOS_PartyReference_C* Party_Id, class UEOS_FriendReference_C* Friend);
	void Create_Party();
	void On_Party_Data_Updated(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, class UMutablePartyData* PartyData);
	void On_Party_Invite_Received(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& SenderId);
	void EOS_Initialize_Party_Events();
	void HandleNetworkError(ENetworkFailure FailureType, bool bIsServer);
	void Update_Session_Settings(const TMap<class FName, struct FOnlineSessionSettingBP>& New_Server_Settings);
	void Find_Previously_Connected_Sessions();
	void Join_Session_From_Session_Id_String(const class FString& Session_Id_0, bool Auto_Connect, bool Bring_Party);
	void Destroy_Current_Session();
	void Destroy_Session(class FName Session_Name);
	void Create_Session_Moderate(class FName Session_Name, const TMap<class FName, struct FOnlineSessionSettingBP>& Server_Settings_0);
	void Create_Session_Advanced(class FName Session_Name, const struct FOnlineSessionSettingsBP& Settings);
	void Join_Session(class FName Session_Name, const struct FOnlineSessionSearchResultBP& Session_Reference, bool Auto_Connect, bool Bring_Party);
	void Find_Sessions();
	void Create_Session(class FName Session_Name);
	void Process_Authorized_Encoded_Request(class UVaRestRequestJSON* Request_JSON, class UVaRestJsonObject* JsonObject, const class FString& Url_Extension);
	void Process_Authorized_Request(class UVaRestRequestJSON* Request_JSON, class UVaRestJsonObject* JsonObject, const class FString& Url_Extension);
	void Receive_Presence(const struct FUniqueNetIdRepl& UserId, const struct FOnlineUserPresenceData& Presence);
	void Initialize_Presence_Events();
	void Get_Presence(const struct FUniqueNetIdRepl& Unique_Id);
	void Change_Presence(const class FString& Presence_Status);
	void Stop_Ping_Matchmaking();
	void Start_Ping_Matchmaking();
	void Remote_Force_Stop_Match_Making();
	void Ping_Matchmaking_Queue_Response(class UVaRestRequestJSON* Request);
	void Ping_Matchmaking_();
	void Stop_Matchmaking_Queue_Response(class UVaRestRequestJSON* Request);
	void Join_Matchmaking_Queue_Response(class UVaRestRequestJSON* Request);
	void Party_Member_Joining_Stopped_Match_Making(const struct FUniqueNetIdRepl& Member_Id);
	void Party_Events_Stopped_Match_Making(bool Successful);
	void Start_Match_Making(E_GameModes Game_Mode);
	void Stop_Match_Making(bool Force, const class FString& Reason);
	void AWS_Initialize_Match_Maker_Events();
	void Game_Services_Connection_Closed(int64 StatusCode, const class FString& Reason, bool bWasClean);
	void Connect_To_Game_Services();
	void Game_Services_Send_Message(const class FString& Message);
	void Game_Services_Message_Sent(const class FString& MessageString);
	void Game_Services_Message_Received(const class FString& MessageString);
	void Game_Services_Connection_Error(const class FString& ConnectionError);
	void Game_Services_Connected();
	void Initialize_Websockets();
	void Received_Session_ID(const class FString& SessionId);
	void Clear_Admin_Session_ID(bool Success, const class FString& Reason);
	void Initialize_Admin_Commands();
	void OnCallFailed_2BE8B34546FB4D223E30AC819336B27A(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Error);
	void OnLoginComplete_2BE8B34546FB4D223E30AC819336B27A(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Error);
	void OnCallFailed_97A8BF3541875BC08341B2B383B4D161(bool bWasSuccessful, class UTexture* ResultTexture);
	void OnGetAvatarComplete_97A8BF3541875BC08341B2B383B4D161(bool bWasSuccessful, class UTexture* ResultTexture);
	void OnCallFailed_0C288BDF4874A442F09639904B36D53E(int32 LocalUserNum, bool bWasSuccessful, const class FString& ListName, const class FString& ErrorStr);
	void OnReadFriendsListComplete_0C288BDF4874A442F09639904B36D53E(int32 LocalUserNum, bool bWasSuccessful, const class FString& ListName, const class FString& ErrorStr);
	void OnCallFailed_4CCA085B4EE35E33E312DE9F76C193C6(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, ELeavePartyCompletionResult_ Result);
	void OnLeavePartyComplete_4CCA085B4EE35E33E312DE9F76C193C6(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, ELeavePartyCompletionResult_ Result);
	void OnCallFailed_7E53908D4B9F239876878F8C1C6A14FB(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& MemberId, EKickMemberCompletionResult_ Result);
	void OnKickPartyMemberComplete_7E53908D4B9F239876878F8C1C6A14FB(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& MemberId, EKickMemberCompletionResult_ Result);
	void OnCallFailed_D9193FAF46512D4925FB5AAC5E694B71(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, EJoinPartyCompletionResult_ Result, int32 NotApprovedReason);
	void OnJoinPartyComplete_D9193FAF46512D4925FB5AAC5E694B71(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, EJoinPartyCompletionResult_ Result, int32 NotApprovedReason);
	void OnCallFailed_32091BA1452A8FA022409C9D5D53760F(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& RecipientId, ESendPartyInvitationCompletionResult_ Result);
	void OnSendPartyInvitationComplete_32091BA1452A8FA022409C9D5D53760F(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, const struct FUniqueNetIdRepl& RecipientId, ESendPartyInvitationCompletionResult_ Result);
	void OnCallFailed_8EAF2E3B4B7F7D0DFD35A4882CD57819(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, ECreatePartyCompletionResult_ Result);
	void OnCreatePartyComplete_8EAF2E3B4B7F7D0DFD35A4882CD57819(const struct FUniqueNetIdRepl& LocalUserId, class UPartyId* PartyId, ECreatePartyCompletionResult_ Result);
	void OnCallFailed_E3F7734C40560B130D78F48346A3CCB0(class FName SessionName, bool bWasSuccessful);
	void OnUpdateSessionComplete_E3F7734C40560B130D78F48346A3CCB0(class FName SessionName, bool bWasSuccessful);
	void OnCallFailed_4B89E9BB4A28A03232A7948C963B204D(bool bWasSuccessful, const TArray<struct FOnlineSessionSearchResultBP>& FriendSearchResult);
	void OnFindFriendSessionComplete_4B89E9BB4A28A03232A7948C963B204D(bool bWasSuccessful, const TArray<struct FOnlineSessionSearchResultBP>& FriendSearchResult);
	void OnCallFailed_ECCF253642672CDE726E0DB1137DB519(int32 LocalUserNum, bool bWasSuccessful, const struct FOnlineSessionSearchResultBP& SearchResult);
	void OnSingleSessionResultComplete_ECCF253642672CDE726E0DB1137DB519(int32 LocalUserNum, bool bWasSuccessful, const struct FOnlineSessionSearchResultBP& SearchResult);
	void OnCallFailed_3F47825A4427C8EDBEB424A49C25FA71(class FName SessionName, bool bWasSuccessful);
	void OnDestroySessionComplete_3F47825A4427C8EDBEB424A49C25FA71(class FName SessionName, bool bWasSuccessful);
	void OnCallFailed_B4AB608F474AFCFD8D0253B744CA3EF2(class FName SessionName, bool bWasSuccessful);
	void OnCreateSessionComplete_B4AB608F474AFCFD8D0253B744CA3EF2(class FName SessionName, bool bWasSuccessful);
	void OnCallFailed_94973A284644EB4A38882BBEBED5E33B(class FName SessionName, EOnJoinSessionCompleteResult_ Result);
	void OnJoinSessionComplete_94973A284644EB4A38882BBEBED5E33B(class FName SessionName, EOnJoinSessionCompleteResult_ Result);
	void OnCallFailed_A2159F9E4575DCCCA2BB228CE2FAB39C(bool bWasSuccessful);
	void OnFindSessionsComplete_A2159F9E4575DCCCA2BB228CE2FAB39C(bool bWasSuccessful);
	void OnCallFailed_11D1165F4D7BF63A2CE88A8B9AFF4C8B(const struct FUniqueNetIdRepl& UserId, bool bWasSuccessful);
	void OnPresenceTaskComplete_11D1165F4D7BF63A2CE88A8B9AFF4C8B(const struct FUniqueNetIdRepl& UserId, bool bWasSuccessful);
	void OnCallFailed_302D1894400B4CD2AEC044B0DFE1862C(const struct FUniqueNetIdRepl& UserId, bool bWasSuccessful);
	void OnPresenceTaskComplete_302D1894400B4CD2AEC044B0DFE1862C(const struct FUniqueNetIdRepl& UserId, bool bWasSuccessful);
	void Is_Signed_In_(bool* Signed_in_);
	void Is_Signed_In_with_Epic_Games_Account_(bool* Signed_In_With_Epic_);
	void Get_Epic_Account_ID(class FString* Epic_ID);
	void Get_Primary_Account_ID(class FString* Account_ID);
	void Get_Product_User_ID(class FString* PUID);
	void Can_Link_To_Epic_Games_Account_(bool* CanLink_);
	void Get_Logged_In_Auth_Attribute(const class FString& Attribute_Name, class FString* Value);
	void Get_User_ID(struct FUniqueNetIdRepl* User_ID);
	void Create_Default_Party_Attributes();
	void Get_Joined_Parties(TArray<class UEOS_PartyReference_C*>* Parties);
	void Get_Party_Members(TArray<class UEOS_PartyMemberReference_C*>* Party_Member_Ids);
	void Is_Party_Leader(bool* IsLeader);
	void Get_Invites(TArray<class UEOS_PartyInviteReference_C*>* Invites);
	void Can_Kick_Member(TArray<class UEOS_PartyReference_C*>* Parties);
	void Get_Current_Session_Id(class FString* Session_Id_0);
	void Get_Players_in_Session(TArray<struct FUniqueNetIdRepl>* Registered_Players, TArray<class FString>* Players_Names);
	void Get_Resolved_Connect_String_From_Session_Name(class FName Session_Name, class FString* Connection_String);
	void Get_Resolved_Connect_String_From_Search_Result(const struct FOnlineSessionSearchResultBP& Search_Result, class FString* Connection_String);
	void Request_Party_Members_Follow_Leader(class FName Session_Name);
	void Get_Player_User_Name(const struct FUniqueNetIdRepl& User_ID, class FString* Nickname);
	void Is_In_Party(bool* In_Party_);
	void Get_Party_Data(class UReadablePartyData** Party_Data);
	void Get_Party_Member_Count(int32* Party_Member_Count);
	void Get_Party_Member_Data(const struct FUniqueNetIdRepl& Member_Id, class UReadablePartyData** Party_Member_Data);
	void Get_Party_Member_Name(const struct FUniqueNetIdRepl& Member_Id, class FString* Name_0);
	void Set_Party_Locked(bool Party_Locked_0);
	void Send_Party_Member_Data_Map(const TMap<class FString, struct FVariantDataBP>& Attributes);
	void Send_Party_Data_Map(const TMap<class FString, struct FVariantDataBP>& Attributes);
	void Is_Member_Party_Leader(const struct FUniqueNetIdRepl& Party_Member, bool* IsLeader);
	void Internal_Update_Server_Settings(const TMap<class FName, struct FOnlineSessionSettingBP>& Server_Settings_0, TMap<class FName, struct FOnlineSessionSettingBP>* Updated_Server_Settings);
	bool Check_If_Should_Leave_Current_Party(class UPartyId* Party_Id);
	EOnlineCachedResult_ Read_Presence(const struct FUniqueNetIdRepl& User_ID, struct FOnlineUserPresenceData* OutPresence);
	void Get_Primary_Platform_Custom(E_Platforms* Primary_Platform);
	void Get_All_Platforms(TArray<class FString>* Platforms);
	void Create_Default_Match_Maker_Attributes();
	void Construct_Matchmaking_Party_Ids(TArray<class FString>* Party_Member_Primary_Account_Net_IDs_as_Strings);
	void Construct_Matchmaking_Join_Request(E_GameModes Game_Mode);
	void Construct_Matchmaking_Stop_Request();
	void Construct_Matchmaking_Ping_Request();
	void Set_Ready_State(bool Ready);
	void Is_Matchmaking_Busy(bool* Matchmaking_Busy);
	void Get_Version(int32* Version_0);
	void Convert_Version(const class FString& String_Version, int32* Version_0);
	void Compare_Version(const class FString& Other_Version);
	void Start_Global_Data_Feed();
	void Construct_Global_Data_Request();
	void Global_Data_Response(class UVaRestRequestJSON* Request);
	void Custom_Popup(const class FText& Title, const class FText& Text, class UUI_DisconnectPopup_C** UI_element);
	void Get_Party_ID(class FString* PartyId);
	void Save_Joined_Session_Data();
	void Load_Joined_Session_Data();
	void Validate_Saved_Session_Data();
	void Force_Reset_Party_Attributes(bool Successful);
	void Session_Follow_Received();
	void Clear_Party_Members();
	void Set_Default_Attributes_on_Personal_Party_Object(class UEOS_PartyMemberReference_C* Party_Member_Reference);
	void Get_Party_Ready(bool* Party_Ready);
	void Calculate_Check_Sum(struct FSHA256Hash* Check_Sum);
	void Compare_Check_Sum(const class FString& A, const class FString& B, const class FString& C, const class FString& D, const struct FSHA256Hash& CheckSum, bool* Valid, class FString* expected);
	void Construct_Matchmaking_Party_Unique_Net_Ids(TArray<class FString>* Party_Member_Unique_Net_IDs_as_Strings);
	void Validate_Matchmaking_Party_Restrictions(bool* Restricted);
	void Handle_Restricted_List(const class FString& Restricted);
	void Restrict_User();
	void Update_Tokens();
	void Get_Steam_Account_ID(class FString* Steam_ID);
	class FString Get_Steam_Token();
	class FString Get_EOS_Token();
	void Find_Avatar(const struct FUniqueNetIdRepl& Key, class UTexture** Avatar, bool* Found);
	void Check_Stored_Session_ID(bool* Has_Session_0);
	void Get_Auth_Token(class FString* Token);
	void Construct_Global_Data_Request_0();
	void Get_Auth_Account_ID(class FString* Account_ID);
	void Get_Auth_Platform(E_Platforms* Auth_Platform);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EOS_GameInstance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EOS_GameInstance_C")
	}
	static class UEOS_GameInstance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEOS_GameInstance_C>();
	}
};
DUMPER7_ASSERTS_UEOS_GameInstance_C;

SDK_NAMESPACE_END
