#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_PlayerState

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function EOS_PlayerState.EOS_PlayerState_C.Set Unique Net Id
// 0x0030 (0x0030 - 0x0000)
struct EOS_PlayerState_C_Set_Unique_Net_Id final
{
public:
	struct FUniqueNetIdRepl                       Unique_Net_Id_0;                                   // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_EOS_PlayerState_C_Set_Unique_Net_Id;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
