#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_FriendReference

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EOS_FriendReference.EOS_FriendReference_C
// 0x0018 (0x0040 - 0x0028)
class UEOS_FriendReference_C final : public UObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOnlineFriendRef*                       Friend;                                            // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          IsSteam;                                           // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsEOS;                                             // 0x0039(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_EOS_FriendReference(int32 EntryPoint);
	void Initialize();
	struct FUniqueNetIdRepl Get_Unique_Net_Id();
	void Get_Platform(class FString* Platform_Name);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EOS_FriendReference_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EOS_FriendReference_C")
	}
	static class UEOS_FriendReference_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEOS_FriendReference_C>();
	}
};
DUMPER7_ASSERTS_UEOS_FriendReference_C;

SDK_NAMESPACE_END
