#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_Party_Member_Replicated_Attribute

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OnlineSubsystemBlueprints_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EOS_Party_Member_Replicated_Attribute.EOS_Party_Member_Replicated_Attribute_C
// 0x00C0 (0x00E8 - 0x0028)
class UEOS_Party_Member_Replicated_Attribute_C final : public UObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEOS_GameInstance_C*                    EOS_Instance;                                      // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       Local_Unique_Net_ID;                               // 0x0038(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       Unique_Net_Id;                                     // 0x0060(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 Key;                                               // 0x0088(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	EOnlineKeyValuePairDataType_                  Type;                                              // 0x0098(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Int;                                               // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 String;                                            // 0x00A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         Float;                                             // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Bool;                                              // 0x00B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_B5[0x3];                                       // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         non_party_int;                                     // 0x00B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 non_party_string;                                  // 0x00C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         non_party_float;                                   // 0x00D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          non_party_bool;                                    // 0x00D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              Values_Changed;                                    // 0x00D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_EOS_Party_Member_Replicated_Attribute(int32 EntryPoint);
	void Force_Retrieve_Party_Member_Data();
	void Party_Member_Data_Received(const struct FUniqueNetIdRepl& Member_Id, class UReadablePartyData* Party_Member_Data);
	void Force_Send_Data(bool Successful);
	void Switch_To_Non_Party(bool Success);
	void Initialize_Party_Member_Attribute();
	void Set_Data(int32 as_Int, const class FString& As_String, float As_Float, bool As_Bool);
	void Get_Data(int32* Int_0, class FString* String_0, float* Float_0, bool* Bool_0);
	void Set_Data_Internal(int32 as_Int, const class FString& As_String, float As_Float, bool As_Bool);
	void Send_Data();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EOS_Party_Member_Replicated_Attribute_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EOS_Party_Member_Replicated_Attribute_C")
	}
	static class UEOS_Party_Member_Replicated_Attribute_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEOS_Party_Member_Replicated_Attribute_C>();
	}
};
DUMPER7_ASSERTS_UEOS_Party_Member_Replicated_Attribute_C;

SDK_NAMESPACE_END
