#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_Voice_Chat_Service

#include "Basic.hpp"

#include "EOS_Voice_Chat_Service_classes.hpp"
#include "EOS_Voice_Chat_Service_parameters.hpp"


SDK_NAMESPACE_START

// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.ExecuteUbergraph_EOS_Voice_Chat_Service
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::ExecuteUbergraph_EOS_Voice_Chat_Service(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "ExecuteUbergraph_EOS_Voice_Chat_Service");

	Params::EOS_Voice_Chat_Service_C_ExecuteUbergraph_EOS_Voice_Chat_Service Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Push To Talk Reset
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Push_To_Talk_Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Push To Talk Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Default Transmit Mode
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Set_Default_Transmit_Mode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Default Transmit Mode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Leave All Voice Channels
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Leave_All_Voice_Channels()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Leave All Voice Channels");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Voice Chat Enabled Property
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Voice_Chat_Enabled_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Set_Voice_Chat_Enabled_Property(bool Voice_Chat_Enabled_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Voice Chat Enabled Property");

	Params::EOS_Voice_Chat_Service_C_Set_Voice_Chat_Enabled_Property Parms{};

	Parms.Voice_Chat_Enabled_0 = Voice_Chat_Enabled_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Push To Talk Property
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Use_Push_To_Talk_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Set_Push_To_Talk_Property(bool Use_Push_To_Talk_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Push To Talk Property");

	Params::EOS_Voice_Chat_Service_C_Set_Push_To_Talk_Property Parms{};

	Parms.Use_Push_To_Talk_0 = Use_Push_To_Talk_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Push To Talk OFF
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Push_To_Talk_OFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Push To Talk OFF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Push To Talk ON
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Push_To_Talk_ON()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Push To Talk ON");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Leave Voice Channel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Leave_Voice_Channel(const class FString& ChannelName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Leave Voice Channel");

	Params::EOS_Voice_Chat_Service_C_Leave_Voice_Channel Parms{};

	Parms.ChannelName = std::move(ChannelName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Logout Voice
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Logout_Voice(bool Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Logout Voice");

	Params::EOS_Voice_Chat_Service_C_Logout_Voice Parms{};

	Parms.Success = Success;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Join Voice Channel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Channel_Name                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    Channel_Credentials                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Join_Voice_Channel(const class FString& Channel_Name, const class FString& Channel_Credentials)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Join Voice Channel");

	Params::EOS_Voice_Chat_Service_C_Join_Voice_Channel Parms{};

	Parms.Channel_Name = std::move(Channel_Name);
	Parms.Channel_Credentials = std::move(Channel_Credentials);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Login
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Voice_Login()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Login");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Chat Player Talking Updated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    bIsTalking                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Voice_Chat_Player_Talking_Updated(const class FString& ChannelName, const class FString& PlayerName, bool bIsTalking)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Chat Player Talking Updated");

	Params::EOS_Voice_Chat_Service_C_Voice_Chat_Player_Talking_Updated Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.PlayerName = std::move(PlayerName);
	Parms.bIsTalking = bIsTalking;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Chat Player Mute Updated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    bIsMuted                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Voice_Chat_Player_Mute_Updated(const class FString& ChannelName, const class FString& PlayerName, bool bIsMuted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Chat Player Mute Updated");

	Params::EOS_Voice_Chat_Service_C_Voice_Chat_Player_Mute_Updated Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.PlayerName = std::move(PlayerName);
	Parms.bIsMuted = bIsMuted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Chat Player Removed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Voice_Chat_Player_Removed(const class FString& ChannelName, const class FString& PlayerName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Chat Player Removed");

	Params::EOS_Voice_Chat_Service_C_Voice_Chat_Player_Removed Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.PlayerName = std::move(PlayerName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Chat Player Added
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Voice_Chat_Player_Added(const class FString& ChannelName, const class FString& PlayerName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Chat Player Added");

	Params::EOS_Voice_Chat_Service_C_Voice_Chat_Player_Added Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.PlayerName = std::move(PlayerName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Chat Channel Exited
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Reason                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::Voice_Chat_Channel_Exited(const class FString& ChannelName, const struct FVoiceChatResultBP& Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Chat Channel Exited");

	Params::EOS_Voice_Chat_Service_C_Voice_Chat_Channel_Exited Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.Reason = std::move(Reason);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Voice Chat Channel Joined
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Voice_Chat_Channel_Joined(const class FString& ChannelName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Voice Chat Channel Joined");

	Params::EOS_Voice_Chat_Service_C_Voice_Chat_Channel_Joined Parms{};

	Parms.ChannelName = std::move(ChannelName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Audio Devices Changed
// (BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Audio_Devices_Changed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Audio Devices Changed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnCallFailed_0A164E9F48F9D6727C740CBCEC072B17
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnCallFailed_0A164E9F48F9D6727C740CBCEC072B17(const class FString& ChannelName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnCallFailed_0A164E9F48F9D6727C740CBCEC072B17");

	Params::EOS_Voice_Chat_Service_C_OnCallFailed_0A164E9F48F9D6727C740CBCEC072B17 Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnVoiceChatChannelLeaveComplete_0A164E9F48F9D6727C740CBCEC072B17
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnVoiceChatChannelLeaveComplete_0A164E9F48F9D6727C740CBCEC072B17(const class FString& ChannelName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnVoiceChatChannelLeaveComplete_0A164E9F48F9D6727C740CBCEC072B17");

	Params::EOS_Voice_Chat_Service_C_OnVoiceChatChannelLeaveComplete_0A164E9F48F9D6727C740CBCEC072B17 Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnCallFailed_DA27C04540EF09EE774270ABBBB3CF51
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnCallFailed_DA27C04540EF09EE774270ABBBB3CF51(const class FString& PlayerName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnCallFailed_DA27C04540EF09EE774270ABBBB3CF51");

	Params::EOS_Voice_Chat_Service_C_OnCallFailed_DA27C04540EF09EE774270ABBBB3CF51 Parms{};

	Parms.PlayerName = std::move(PlayerName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnVoiceChatLogoutComplete_DA27C04540EF09EE774270ABBBB3CF51
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnVoiceChatLogoutComplete_DA27C04540EF09EE774270ABBBB3CF51(const class FString& PlayerName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnVoiceChatLogoutComplete_DA27C04540EF09EE774270ABBBB3CF51");

	Params::EOS_Voice_Chat_Service_C_OnVoiceChatLogoutComplete_DA27C04540EF09EE774270ABBBB3CF51 Parms{};

	Parms.PlayerName = std::move(PlayerName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnCallFailed_933CD2BA4E95D1B9C48B58AF1158DDBE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnCallFailed_933CD2BA4E95D1B9C48B58AF1158DDBE(const class FString& ChannelName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnCallFailed_933CD2BA4E95D1B9C48B58AF1158DDBE");

	Params::EOS_Voice_Chat_Service_C_OnCallFailed_933CD2BA4E95D1B9C48B58AF1158DDBE Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnVoiceChatChannelJoinComplete_933CD2BA4E95D1B9C48B58AF1158DDBE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ChannelName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnVoiceChatChannelJoinComplete_933CD2BA4E95D1B9C48B58AF1158DDBE(const class FString& ChannelName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnVoiceChatChannelJoinComplete_933CD2BA4E95D1B9C48B58AF1158DDBE");

	Params::EOS_Voice_Chat_Service_C_OnVoiceChatChannelJoinComplete_933CD2BA4E95D1B9C48B58AF1158DDBE Parms{};

	Parms.ChannelName = std::move(ChannelName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnCallFailed_57A16C70489EFA960C91F48E326DB441
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnCallFailed_57A16C70489EFA960C91F48E326DB441(const class FString& PlayerName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnCallFailed_57A16C70489EFA960C91F48E326DB441");

	Params::EOS_Voice_Chat_Service_C_OnCallFailed_57A16C70489EFA960C91F48E326DB441 Parms{};

	Parms.PlayerName = std::move(PlayerName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.OnVoiceChatLoginComplete_57A16C70489EFA960C91F48E326DB441
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FVoiceChatResultBP&        Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void AEOS_Voice_Chat_Service_C::OnVoiceChatLoginComplete_57A16C70489EFA960C91F48E326DB441(const class FString& PlayerName, const struct FVoiceChatResultBP& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "OnVoiceChatLoginComplete_57A16C70489EFA960C91F48E326DB441");

	Params::EOS_Voice_Chat_Service_C_OnVoiceChatLoginComplete_57A16C70489EFA960C91F48E326DB441 Parms{};

	Parms.PlayerName = std::move(PlayerName);
	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Available Input Devices
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FString>*                  Devices                                                (Parm, OutParm)

void AEOS_Voice_Chat_Service_C::Get_Available_Input_Devices(TArray<class FString>* Devices)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Available Input Devices");

	Params::EOS_Voice_Chat_Service_C_Get_Available_Input_Devices Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Devices != nullptr)
		*Devices = std::move(Parms.Devices);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Available Output Devices
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FString>*                  Devices                                                (Parm, OutParm)

void AEOS_Voice_Chat_Service_C::Get_Available_Output_Devices(TArray<class FString>* Devices)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Available Output Devices");

	Params::EOS_Voice_Chat_Service_C_Get_Available_Output_Devices Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Devices != nullptr)
		*Devices = std::move(Parms.Devices);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Current Input Device
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          Device                                                 (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Get_Current_Input_Device(class FString* Device)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Current Input Device");

	Params::EOS_Voice_Chat_Service_C_Get_Current_Input_Device Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Device != nullptr)
		*Device = std::move(Parms.Device);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Current Output Device
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          Device                                                 (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Get_Current_Output_Device(class FString* Device)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Current Output Device");

	Params::EOS_Voice_Chat_Service_C_Get_Current_Output_Device Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Device != nullptr)
		*Device = std::move(Parms.Device);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Input Device
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Device                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Set_Input_Device(const class FString& Device)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Input Device");

	Params::EOS_Voice_Chat_Service_C_Set_Input_Device Parms{};

	Parms.Device = std::move(Device);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Output Device
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Device                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Set_Output_Device(const class FString& Device)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Output Device");

	Params::EOS_Voice_Chat_Service_C_Set_Output_Device Parms{};

	Parms.Device = std::move(Device);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Is Logged In?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Logged_in                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Is_Logged_In_(bool* Logged_in)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Is Logged In?");

	Params::EOS_Voice_Chat_Service_C_Is_Logged_In_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Logged_in != nullptr)
		*Logged_in = Parms.Logged_in;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Logged In Player Name
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          Player_Name                                            (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Get_Logged_In_Player_Name(class FString* Player_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Logged In Player Name");

	Params::EOS_Voice_Chat_Service_C_Get_Logged_In_Player_Name Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Player_Name != nullptr)
		*Player_Name = std::move(Parms.Player_Name);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Is Connected?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Connected                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Is_Connected_(bool* Connected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Is Connected?");

	Params::EOS_Voice_Chat_Service_C_Is_Connected_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Connected != nullptr)
		*Connected = Parms.Connected;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Is Connecting?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Connecting                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Is_Connecting_(bool* Connecting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Is Connecting?");

	Params::EOS_Voice_Chat_Service_C_Is_Connecting_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Connecting != nullptr)
		*Connecting = Parms.Connecting;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Joined Channels
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UEOS_VoiceChannel_Referemce_C*>*Channels                                               (Parm, OutParm)

void AEOS_Voice_Chat_Service_C::Get_Joined_Channels(TArray<class UEOS_VoiceChannel_Referemce_C*>* Channels)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Joined Channels");

	Params::EOS_Voice_Chat_Service_C_Get_Joined_Channels Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Channels != nullptr)
		*Channels = std::move(Parms.Channels);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Players In Channel
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UEOS_VoiceChannel_Referemce_C*    Channel                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UEOS_Voice_Chat_Participant_Reference_C*>*Participants                                           (Parm, OutParm)

void AEOS_Voice_Chat_Service_C::Get_Players_In_Channel(class UEOS_VoiceChannel_Referemce_C* Channel, TArray<class UEOS_Voice_Chat_Participant_Reference_C*>* Participants)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Players In Channel");

	Params::EOS_Voice_Chat_Service_C_Get_Players_In_Channel Parms{};

	Parms.Channel = Channel;

	UObject::ProcessEvent(Func, &Parms);

	if (Participants != nullptr)
		*Participants = std::move(Parms.Participants);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Input Muted
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Muted                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Get_Input_Muted(bool* Muted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Input Muted");

	Params::EOS_Voice_Chat_Service_C_Get_Input_Muted Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Muted != nullptr)
		*Muted = Parms.Muted;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Input Volume
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Volume                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Get_Input_Volume(float* Volume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Input Volume");

	Params::EOS_Voice_Chat_Service_C_Get_Input_Volume Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Volume != nullptr)
		*Volume = Parms.Volume;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Output Muted
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Muted                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Get_Output_Muted(bool* Muted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Output Muted");

	Params::EOS_Voice_Chat_Service_C_Get_Output_Muted Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Muted != nullptr)
		*Muted = Parms.Muted;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Output Volume
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  Volume                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Get_Output_Volume(float* Volume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Output Volume");

	Params::EOS_Voice_Chat_Service_C_Get_Output_Volume Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Volume != nullptr)
		*Volume = Parms.Volume;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Get Transmit Mode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EVoiceChatTransmitMode_                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EVoiceChatTransmitMode_ AEOS_Voice_Chat_Service_C::Get_Transmit_Mode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Get Transmit Mode");

	Params::EOS_Voice_Chat_Service_C_Get_Transmit_Mode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Input Muted
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Muted                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Set_Input_Muted(bool Muted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Input Muted");

	Params::EOS_Voice_Chat_Service_C_Set_Input_Muted Parms{};

	Parms.Muted = Muted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Input Volume
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Volume                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Set_Input_Volume(float Volume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Input Volume");

	Params::EOS_Voice_Chat_Service_C_Set_Input_Volume Parms{};

	Parms.Volume = Volume;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Output Muted
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Muted                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AEOS_Voice_Chat_Service_C::Set_Output_Muted(bool Muted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Output Muted");

	Params::EOS_Voice_Chat_Service_C_Set_Output_Muted Parms{};

	Parms.Muted = Muted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Output Volume
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Volume                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Set_Output_Volume(float Volume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Output Volume");

	Params::EOS_Voice_Chat_Service_C_Set_Output_Volume Parms{};

	Parms.Volume = Volume;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Set Transmit Mode
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EVoiceChatTransmitMode_                 Transmit_Mode                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEOS_Voice_Chat_Service_C::Set_Transmit_Mode(EVoiceChatTransmitMode_ Transmit_Mode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Set Transmit Mode");

	Params::EOS_Voice_Chat_Service_C_Set_Transmit_Mode Parms{};

	Parms.Transmit_Mode = Transmit_Mode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EOS_Voice_Chat_Service.EOS_Voice_Chat_Service_C.Load Settings From BP Game Instance
// (Public, BlueprintCallable, BlueprintEvent)

void AEOS_Voice_Chat_Service_C::Load_Settings_From_BP_Game_Instance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EOS_Voice_Chat_Service_C", "Load Settings From BP Game Instance");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
