#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EOS_Party_Member_Ship

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "E_ShipTypes_structs.hpp"
#include "ST_ShipCustomisations_renamed_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EOS_Party_Member_Ship.EOS_Party_Member_Ship_C
// 0x0150 (0x0370 - 0x0220)
class AEOS_Party_Member_Ship_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       LoadingWidget;                                     // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUI_Party_Member_Username_C*            MemberInfoWidgetRef;                               // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           TimeoutTimer;                                      // 0x0240(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FST_ShipCustomisations_renamed         Cached_Cosmetics;                                  // 0x0248(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Cached_Curse;                                      // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C1[0x7];                                      // 0x02C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       Party_Member_Id;                                   // 0x02C8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UEOS_PartyMemberReference_C*            EOS_Party_Member_Reference;                        // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class ABP_Mannequin_C*                        Mannequin;                                         // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Level;                                             // 0x0300(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 UserName;                                          // 0x0308(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class AEOS_Party_Member_Position_C*           Manager_Ref;                                       // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          My_Ship;                                           // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_BoatMeshBase_C*                     Ship_Ref;                                          // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_ShipTypes                                   Spawned_Ship_Type;                                 // 0x0330(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_331[0xF];                                      // 0x0331(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             ShipTransform;                                     // 0x0340(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_EOS_Party_Member_Ship(int32 EntryPoint);
	void Ship_Cosmetics_Updated(const struct FST_ShipCustomisations_renamed& Ship_Cosmetics);
	void Initialize();
	void Bind_To_EOS_Events();
	void ReceiveBeginPlay();
	void Update_Ship_Cosmetics(const struct FST_ShipCustomisations_renamed& Cached_Cosmetics_0);
	void Reevaluate_This_Member();
	void Check_If_Mine();
	void Finished_Loading();
	void Update_Ship(const struct FST_ShipCustomisations_renamed& Ship_Cosmetics);
	void Manually_Update_Data();
	void Update_Ship_Reference_on_Controller();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EOS_Party_Member_Ship_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EOS_Party_Member_Ship_C")
	}
	static class AEOS_Party_Member_Ship_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEOS_Party_Member_Ship_C>();
	}
};
DUMPER7_ASSERTS_AEOS_Party_Member_Ship_C;

SDK_NAMESPACE_END
