#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GunGame_Alpha_GameMode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Alpha_GameMode_classes.hpp"
#include "E_Weapons_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GunGame_Alpha_GameMode.GunGame_Alpha_GameMode_C
// 0x0018 (0x04C8 - 0x04B0)
class AGunGame_Alpha_GameMode_C final : public AAlpha_GameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GunGame_Alpha_GameMode_C;           // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class AActor*>                         Possible_Spawn_Points;                             // 0x04B8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GunGame_Alpha_GameMode(int32 EntryPoint);
	void CharacterSpawned(bool Force, class APawn* Character, class AAlpha_PlayerController_C* Controller);
	void ReceiveBeginPlay();
	void Start_Game_Custom_Game_Mode();
	void Teleport_All_Players_To_Start_Position();
	void Get_Unique_Start_Positions(int32 Amount_of_Positions_Needed, TArray<class AActor*>* Picked_Start_Locations);
	void Handle_Crew_Member_Kill_(class AAlpha_PlayerState_C* Killer_Player_State, class AAlpha_PlayerState_C* Killed_Player_State, E_Weapons Weapon);
	void Give_Weapon_to_Player(class ABP_Character_C* Character_Ref, int32 Weapon_Level, bool Play_Sound_Effect);
	void Defeat_All_Other_Teams(class AAlpha_PlayerState_C* Winning_Player_State);
	void Find_All_Possible_Spawn_Points();
	void Increase_Weapon_Level_(class UObject* Object);
	void Sanitize_Weapon_Order_And_Apply();
	void Give_Chests(class ANewTeamManager_C* Team_Manager, class UInventoryTracker_C* Inventory_Tracker, TArray<int32>& Levels_Gained);
	void Character_Start_Setup_(class AAlpha_PlayerController_C* Controller, class ACharacter* Character);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GunGame_Alpha_GameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GunGame_Alpha_GameMode_C")
	}
	static class AGunGame_Alpha_GameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGunGame_Alpha_GameMode_C>();
	}
};
DUMPER7_ASSERTS_AGunGame_Alpha_GameMode_C;

SDK_NAMESPACE_END
