#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Menu_Alpha_Game_State

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Alpha_Game_State_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Menu_Alpha_Game_State.Menu_Alpha_Game_State_C
// 0x0008 (0x0690 - 0x0688)
class AMenu_Alpha_Game_State_C final : public AAlpha_Game_State_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Menu_Alpha_Game_State_C;            // 0x0688(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Menu_Alpha_Game_State(int32 EntryPoint);
	void Set_Discord_Data();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Menu_Alpha_Game_State_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Menu_Alpha_Game_State_C")
	}
	static class AMenu_Alpha_Game_State_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMenu_Alpha_Game_State_C>();
	}
};
DUMPER7_ASSERTS_AMenu_Alpha_Game_State_C;

SDK_NAMESPACE_END
