#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewCrewManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "E_ShipTypes_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass NewCrewManager.NewCrewManager_C
// 0x00D0 (0x02F0 - 0x0220)
class ANewCrewManager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTeam_Crew_Ship_Member_State_C*         Team_Crew_Ship_Member_State;                       // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ANewTeamManager_C*                      Team_Manager_Ref;                                  // 0x0238(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class ANewShipManager_C*                      Ship_Manager_Ref;                                  // 0x0240(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AAlpha_PlayerState_C*>           Crew_Members;                                      // 0x0248(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance, RepNotify)
	TMulticastInlineDelegate<void(class ANewCrewManager_C* Crew)> On_Crew_Defeated;                  // 0x0258(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              On_Ship_Spawned;                                   // 0x0268(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(E_ShipTypes New_Ship_Type)> On_Ship_Change_Type;                   // 0x0278(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              On_Ship_Despawn;                                   // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              On_Crew_Updated;                                   // 0x0298(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class AAlpha_PlayerState_C*                   Leader;                                            // 0x02A8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Leader_Set;                                        // 0x02B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Crew_Defeated;                                     // 0x02B1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B2[0x6];                                      // 0x02B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FUniqueNetIdRepl>               Restricted_List;                                   // 0x02B8(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	bool                                          Crew_Locked;                                       // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Crew_Size_Unlocked;                                // 0x02C9(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2CA[0x6];                                      // 0x02CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              On_Leader_Changed;                                 // 0x02D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         Max_Crew_Size;                                     // 0x02E0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         Ship_Based_Max_Crew_Size;                          // 0x02E4(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           Crew_Validator_timer;                              // 0x02E8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_NewCrewManager(int32 EntryPoint);
	void Validate_Team();
	void Initialize_Crew();
	void Defeat_Ship();
	void Defeat_Crew(float Delay, float Delay_Deaths, bool Defeat_Crew_Members_0);
	void Defeat_Crew_Members(float Delay, bool Defeated);
	void Remove_Player(class AAlpha_PlayerState_C* Alpha_Player_State);
	void Check_if_Should_Auto_Defeat();
	void Check_If_Should_Set_Leader(class AAlpha_PlayerState_C* Alpha_Player_State);
	int32 Get_Crew_Size();
	void Check_if_Ship_Is_Defeated(bool* All_Ships_Defeated);
	void Create_Ship_Manager(int32 Ship_ID, class ANewShipManager_C** Ship_Manager);
	void AddPlayer(class AAlpha_PlayerState_C* Alpha_Player_State, bool* Success);
	void OnRep_Leader();
	void Find_Available_Crew_Member_ID(int32* Available_Crew_Member_ID);
	void Set_Leader(class AAlpha_PlayerState_C* Alpha_Player_State);
	void Filter_Test(const struct FUniqueNetIdRepl& Unique_Net_Id, bool* Available_Crew);
	void Has_Party_Leader_In_Crew(const class FString& Party_Id, bool* Has_Party_Host_In_Crew);
	void Find_New_Leader();
	void Get_Leader(class AAlpha_PlayerState_C** Leader_0);
	void OnRep_Crew_Members();
	void Check_If_Crew_Is_Empty(bool* Empty);
	void Get_Max_Crew_Size(int32* Max_Crew_Size_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NewCrewManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NewCrewManager_C")
	}
	static class ANewCrewManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANewCrewManager_C>();
	}
};
DUMPER7_ASSERTS_ANewCrewManager_C;

SDK_NAMESPACE_END
