#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewTeamManager

#include "Basic.hpp"

#include "NewTeamManager_classes.hpp"
#include "NewTeamManager_parameters.hpp"


SDK_NAMESPACE_START

// Function NewTeamManager.NewTeamManager_C.ExecuteUbergraph_NewTeamManager
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::ExecuteUbergraph_NewTeamManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "ExecuteUbergraph_NewTeamManager");

	Params::NewTeamManager_C_ExecuteUbergraph_NewTeamManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeamManager.NewTeamManager_C.Remove Player
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                Player_Controller                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Crew_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Remove_Player(class APlayerController* Player_Controller, int32 Crew_ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Remove Player");

	Params::NewTeamManager_C_Remove_Player Parms{};

	Parms.Player_Controller = Player_Controller;
	Parms.Crew_ID = Crew_ID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeamManager.NewTeamManager_C.Fire Ship or Crew Amount Updated
// (BlueprintCallable, BlueprintEvent)

void ANewTeamManager_C::Fire_Ship_or_Crew_Amount_Updated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Fire Ship or Crew Amount Updated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeamManager.NewTeamManager_C.Bind to Crew Events
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANewCrewManager_C*                Crew                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Bind_to_Crew_Events(class ANewCrewManager_C* Crew)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Bind to Crew Events");

	Params::NewTeamManager_C_Bind_to_Crew_Events Parms{};

	Parms.Crew = Crew;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeamManager.NewTeamManager_C.Defeat Team
// (BlueprintCallable, BlueprintEvent)

void ANewTeamManager_C::Defeat_Team()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Defeat Team");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeamManager.NewTeamManager_C.Get Spawn Point
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BoatSpawn_C**                 Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Get_Spawn_Point(class ABP_BoatSpawn_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get Spawn Point");

	Params::NewTeamManager_C_Get_Spawn_Point Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function NewTeamManager.NewTeamManager_C.Find Crew with ID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Crew_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ANewCrewManager_C**               Crew_Manager                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Found                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ANewTeamManager_C::Find_Crew_with_ID(int32 Crew_ID, class ANewCrewManager_C** Crew_Manager, bool* Found)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Find Crew with ID");

	Params::NewTeamManager_C_Find_Crew_with_ID Parms{};

	Parms.Crew_ID = Crew_ID;

	UObject::ProcessEvent(Func, &Parms);

	if (Crew_Manager != nullptr)
		*Crew_Manager = Parms.Crew_Manager;

	if (Found != nullptr)
		*Found = Parms.Found;
}


// Function NewTeamManager.NewTeamManager_C.Create Crew Manager
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Crew_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AAlpha_PlayerState_C*             Crew_Leader                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ANewCrewManager_C**               Crew_Manager                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Create_Crew_Manager(int32 Crew_ID, class AAlpha_PlayerState_C* Crew_Leader, class ANewCrewManager_C** Crew_Manager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Create Crew Manager");

	Params::NewTeamManager_C_Create_Crew_Manager Parms{};

	Parms.Crew_ID = Crew_ID;
	Parms.Crew_Leader = Crew_Leader;

	UObject::ProcessEvent(Func, &Parms);

	if (Crew_Manager != nullptr)
		*Crew_Manager = Parms.Crew_Manager;
}


// Function NewTeamManager.NewTeamManager_C.Delete Crew Manager
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Crew_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ANewTeamManager_C::Delete_Crew_Manager(int32 Crew_ID, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Delete Crew Manager");

	Params::NewTeamManager_C_Delete_Crew_Manager Parms{};

	Parms.Crew_ID = Crew_ID;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function NewTeamManager.NewTeamManager_C.Check If Team Is Empty
// (Public, BlueprintCallable, BlueprintEvent)

void ANewTeamManager_C::Check_If_Team_Is_Empty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Check If Team Is Empty");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeamManager.NewTeamManager_C.Set Team Rank
// (Public, BlueprintCallable, BlueprintEvent)

void ANewTeamManager_C::Set_Team_Rank()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Set Team Rank");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeamManager.NewTeamManager_C.Get Team Score
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Total_Team_Score                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Get_Team_Score(int32* Total_Team_Score)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get Team Score");

	Params::NewTeamManager_C_Get_Team_Score Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Total_Team_Score != nullptr)
		*Total_Team_Score = Parms.Total_Team_Score;
}


// Function NewTeamManager.NewTeamManager_C.Get Team Name
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText*                            Team_Name_0                                            (Parm, OutParm)

void ANewTeamManager_C::Get_Team_Name(class FText* Team_Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get Team Name");

	Params::NewTeamManager_C_Get_Team_Name Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Team_Name_0 != nullptr)
		*Team_Name_0 = std::move(Parms.Team_Name_0);
}


// Function NewTeamManager.NewTeamManager_C.Update Team Name
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ANewCrewManager_C*                Crew_Manager                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Update_Team_Name(class ANewCrewManager_C* Crew_Manager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Update Team Name");

	Params::NewTeamManager_C_Update_Team_Name Parms{};

	Parms.Crew_Manager = Crew_Manager;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeamManager.NewTeamManager_C.Set Team Rank Custom
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Rank_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Set_Team_Rank_Custom(int32 Rank_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Set Team Rank Custom");

	Params::NewTeamManager_C_Set_Team_Rank_Custom Parms{};

	Parms.Rank_0 = Rank_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeamManager.NewTeamManager_C.Add Player To Team
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                Player_Controller                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Crew_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ANewTeamManager_C::Add_Player_To_Team(class APlayerController* Player_Controller, int32 Crew_ID, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Add Player To Team");

	Params::NewTeamManager_C_Add_Player_To_Team Parms{};

	Parms.Player_Controller = Player_Controller;
	Parms.Crew_ID = Crew_ID;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function NewTeamManager.NewTeamManager_C.Get All Player Controller 
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AAlpha_PlayerController_C*>*Team_Player_Controllers                                (Parm, OutParm)

void ANewTeamManager_C::Get_All_Player_Controller_(TArray<class AAlpha_PlayerController_C*>* Team_Player_Controllers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get All Player Controller ");

	Params::NewTeamManager_C_Get_All_Player_Controller_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Team_Player_Controllers != nullptr)
		*Team_Player_Controllers = std::move(Parms.Team_Player_Controllers);
}


// Function NewTeamManager.NewTeamManager_C.Construct 
// (Public, BlueprintCallable, BlueprintEvent)

void ANewTeamManager_C::Construct_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Construct ");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeamManager.NewTeamManager_C.Get Team Player Size
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Team_Player_Size                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Get_Team_Player_Size(int32* Team_Player_Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get Team Player Size");

	Params::NewTeamManager_C_Get_Team_Player_Size Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Team_Player_Size != nullptr)
		*Team_Player_Size = Parms.Team_Player_Size;
}


// Function NewTeamManager.NewTeamManager_C.Add Restricted Player To Team
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUniqueNetIdRepl&          Restricted_Unique_Net_ID_                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void ANewTeamManager_C::Add_Restricted_Player_To_Team(const struct FUniqueNetIdRepl& Restricted_Unique_Net_ID_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Add Restricted Player To Team");

	Params::NewTeamManager_C_Add_Restricted_Player_To_Team Parms{};

	Parms.Restricted_Unique_Net_ID_ = std::move(Restricted_Unique_Net_ID_);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeamManager.NewTeamManager_C.Filter Test
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUniqueNetIdRepl&          Unique_Net_Id                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// bool                                    Pre_Made_Team_Check                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool*                                   Available_Team                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ANewTeamManager_C::Filter_Test(const struct FUniqueNetIdRepl& Unique_Net_Id, bool Pre_Made_Team_Check, bool* Available_Team)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Filter Test");

	Params::NewTeamManager_C_Filter_Test Parms{};

	Parms.Unique_Net_Id = std::move(Unique_Net_Id);
	Parms.Pre_Made_Team_Check = Pre_Made_Team_Check;

	UObject::ProcessEvent(Func, &Parms);

	if (Available_Team != nullptr)
		*Available_Team = Parms.Available_Team;
}


// Function NewTeamManager.NewTeamManager_C.OnRep_CrewManagers
// (BlueprintCallable, BlueprintEvent)

void ANewTeamManager_C::OnRep_CrewManagers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "OnRep_CrewManagers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeamManager.NewTeamManager_C.Get Available Crew ID
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Available_Crew_ID                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Get_Available_Crew_ID(int32* Available_Crew_ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get Available Crew ID");

	Params::NewTeamManager_C_Get_Available_Crew_ID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Available_Crew_ID != nullptr)
		*Available_Crew_ID = Parms.Available_Crew_ID;
}


// Function NewTeamManager.NewTeamManager_C.Crew Count
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  Crew_Count_0                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Crew_Count(int32* Crew_Count_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Crew Count");

	Params::NewTeamManager_C_Crew_Count Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Crew_Count_0 != nullptr)
		*Crew_Count_0 = Parms.Crew_Count_0;
}


// Function NewTeamManager.NewTeamManager_C.Get Crew Size Info
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Crew_ID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Crew_Size                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANewTeamManager_C::Get_Crew_Size_Info(int32 Crew_ID, int32* Crew_Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeamManager_C", "Get Crew Size Info");

	Params::NewTeamManager_C_Get_Crew_Size_Info Parms{};

	Parms.Crew_ID = Crew_ID;

	UObject::ProcessEvent(Func, &Parms);

	if (Crew_Size != nullptr)
		*Crew_Size = Parms.Crew_Size;
}


SDK_NAMESPACE_END
