#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerTracker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "ST_PlayerTrackerExperience_Data_renamed_structs.hpp"
#include "VaRest_structs.hpp"
#include "E_GameModes_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PlayerTracker.PlayerTracker_C
// 0x0128 (0x01D8 - 0x00B0)
class UPlayerTracker_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_BaseController_C*                   Controller;                                        // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                SteamEcoManagerRef;                                // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RequiredExperiencePerLevel;                        // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDateTime                              StartPlayTime;                                     // 0x00D0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, RepNotify, NoDestructor, HasGetValueTypeHash)
	struct FST_PlayerTrackerExperience_Data_renamed Experience_Data;                                 // 0x00D8(0x00A8)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, RepNotify, HasGetValueTypeHash)
	bool                                          DisableProgression;                                // 0x0180(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          UsedQuickPlay;                                     // 0x0181(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	E_GameModes                                   GameMode;                                          // 0x0182(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsPartyLeader;                                     // 0x0183(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FST_PlayerTrackerExperience_Data_renamed& Experience_Data_0)> Received_Player_Experience_Data; // 0x0188(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          HasExperience_Data;                                // 0x0198(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 Last_Received_Levels;                              // 0x01A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Replicated_Last_Received_Levels;                   // 0x01B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B1[0x3];                                      // 0x01B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         attempt_count;                                     // 0x01B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Replicated_Start_Play_Time;                        // 0x01B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVaRestJsonObject*                      json_additional_data;                              // 0x01C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           Validation_Timer;                                  // 0x01C8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          Requested_Validation;                              // 0x01D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_PlayerTracker(int32 EntryPoint);
	void OC_Validate_Internal_Modules();
	void S_Validated_Internal_Folder(const class FString& ValidationString);
	void Validate_Internal_References();
	void StartTracking();
	void Initialize_Player_Tracker();
	void ReceiveBeginPlay();
	void OC_Show_Levels(const TArray<int32>& Received_Levels);
	void SetStartPlayTime(const struct FDateTime& StartTime);
	void GetPlayTime(int32* playTime);
	void Process_XP_and_Write_Player_and_Match_Data_to_Server(bool DontRewardXP, TArray<int32>* GainedLevels);
	void SetStartPlayTimeNow();
	void WritePlayerToServer();
	void ProcessScoreGained(bool won, TArray<int32>* GainedLevels);
	void WriteMatchDetailsToServer();
	void ReadPlayerFromServer();
	void ProcessPlayerDataFromServer(class UVaRestRequestJSON* Response);
	void ProcessLevelRewards(const struct FST_PlayerTrackerExperience_Data_renamed& ExperienceData, TArray<int32>* GainedLevels);
	void OnRep_Experience_Data();
	void CheckForEXPFarming(int32 ScoreGained, int32 Duration);
	void Add_Game_Played(E_GameModes GameMode_0, bool won, bool Cursed, TArray<int32>* GainedLevels);
	void Reset_Last_Received_Levels();
	void OnRep_StartPlayTime();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PlayerTracker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerTracker_C")
	}
	static class UPlayerTracker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerTracker_C>();
	}
};
DUMPER7_ASSERTS_UPlayerTracker_C;

SDK_NAMESPACE_END
