#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RHIManager

#include "Basic.hpp"

#include "RHIManager_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function RHIManager.RHIManagerBPLibrary.GetCurrentGraphicsRHI
// 0x0001 (0x0001 - 0x0000)
struct RHIManagerBPLibrary_GetCurrentGraphicsRHI final
{
public:
	EGraphicsRHI                                  ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RHIManagerBPLibrary_GetCurrentGraphicsRHI;

// Function RHIManager.RHIManagerBPLibrary.RHIManagerSampleFunction
// 0x0008 (0x0008 - 0x0000)
struct RHIManagerBPLibrary_RHIManagerSampleFunction final
{
public:
	float                                         Param;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RHIManagerBPLibrary_RHIManagerSampleFunction;

// Function RHIManager.RHIManagerBPLibrary.SetGraphicsRHI
// 0x0001 (0x0001 - 0x0000)
struct RHIManagerBPLibrary_SetGraphicsRHI final
{
public:
	EGraphicsRHI                                  GraphicsRHI;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RHIManagerBPLibrary_SetGraphicsRHI;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
