#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RHIManager

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "RHIManager_structs.hpp"


SDK_NAMESPACE_START

// Class RHIManager.RHIManagerBPLibrary
// 0x0000 (0x0028 - 0x0028)
class URHIManagerBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static EGraphicsRHI GetCurrentGraphicsRHI();
	static float RHIManagerSampleFunction(float Param);
	static void SetGraphicsRHI(EGraphicsRHI GraphicsRHI);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RHIManagerBPLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RHIManagerBPLibrary")
	}
	static class URHIManagerBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<URHIManagerBPLibrary>();
	}
};
DUMPER7_ASSERTS_URHIManagerBPLibrary;

SDK_NAMESPACE_END
