#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SG_Presets

#include "Basic.hpp"

#include "SG_Presets_classes.hpp"
#include "SG_Presets_parameters.hpp"


SDK_NAMESPACE_START

// Function SG_Presets.SG_Presets_C.Compare Ship Cosmetics
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USG_Presets_C*                    Other_Presets                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Different                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USG_Presets_C::Compare_Ship_Cosmetics(class USG_Presets_C* Other_Presets, bool* Different)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SG_Presets_C", "Compare Ship Cosmetics");

	Params::SG_Presets_C_Compare_Ship_Cosmetics Parms{};

	Parms.Other_Presets = Other_Presets;

	UObject::ProcessEvent(Func, &Parms);

	if (Different != nullptr)
		*Different = Parms.Different;
}


// Function SG_Presets.SG_Presets_C.Compare Player Cosmetics
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USG_Presets_C*                    Other_Presets                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Different                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USG_Presets_C::Compare_Player_Cosmetics(class USG_Presets_C* Other_Presets, bool* Different)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SG_Presets_C", "Compare Player Cosmetics");

	Params::SG_Presets_C_Compare_Player_Cosmetics Parms{};

	Parms.Other_Presets = Other_Presets;

	UObject::ProcessEvent(Func, &Parms);

	if (Different != nullptr)
		*Different = Parms.Different;
}


// Function SG_Presets.SG_Presets_C.Compare String Arrays
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FString>&                  Primary_Array                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<class FString>&                  Secondary_Array                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   Different                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USG_Presets_C::Compare_String_Arrays(TArray<class FString>& Primary_Array, TArray<class FString>& Secondary_Array, bool* Different)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SG_Presets_C", "Compare String Arrays");

	Params::SG_Presets_C_Compare_String_Arrays Parms{};

	Parms.Primary_Array = std::move(Primary_Array);
	Parms.Secondary_Array = std::move(Secondary_Array);

	UObject::ProcessEvent(Func, &Parms);

	Primary_Array = std::move(Parms.Primary_Array);
	Secondary_Array = std::move(Parms.Secondary_Array);

	if (Different != nullptr)
		*Different = Parms.Different;
}


// Function SG_Presets.SG_Presets_C.Compare Presets Other
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USG_Presets_C*                    Other_Presets                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Different                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USG_Presets_C::Compare_Presets_Other(class USG_Presets_C* Other_Presets, bool* Different)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SG_Presets_C", "Compare Presets Other");

	Params::SG_Presets_C_Compare_Presets_Other Parms{};

	Parms.Other_Presets = Other_Presets;

	UObject::ProcessEvent(Func, &Parms);

	if (Different != nullptr)
		*Different = Parms.Different;
}


SDK_NAMESPACE_END
