#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SG_SaveGame

#include "Basic.hpp"

#include "E_ShipTypes_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SG_SaveGame.SG_SaveGame_C
// 0x00C8 (0x00F0 - 0x0028)
class USG_SaveGame_C final : public USaveGame
{
public:
	TArray<class FText>                           UsedCodes;                                         // 0x0028(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Dv;                                                // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	E_ShipTypes                                   SelectedShipType;                                  // 0x0039(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FUniqueNetIdRepl>               MutedPlayerList;                                   // 0x0040(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<E_ShipTypes, class FString>              Ship_Customizations_Strings;                       // 0x0050(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 Player_Customizations_String;                      // 0x00A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 Sort_Settings_String;                              // 0x00B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Streamer_Mode;                                     // 0x00C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Pirate_Curse;                                      // 0x00C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C2[0x6];                                       // 0x00C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Server_Host_Settings_String;                       // 0x00C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 Server_Host_GunGame_Settings_String;               // 0x00D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          HasPlayerTutorial;                                 // 0x00E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Compare_Save_Game(class USG_SaveGame_C* Other_Save_Game, bool* Different);
	void Compare_Muted_Players(class USG_SaveGame_C* Other_Save_Game, bool* Different);
	void Compare_Ship_Customization(class USG_SaveGame_C* Other_Save_Game, bool* Different);
	void Compare_Player_Customization(class USG_SaveGame_C* Other_Save_Game, bool* Different);
	void Compare_Used_Codes(class USG_SaveGame_C* Other_Save_Game, bool* Different);
	void Set_Ship_Customizations(const TMap<E_ShipTypes, struct FST_ShipCustomisations_renamed>& Ship_Customization_Structs);
	void Get_Ship_Customizations(TMap<E_ShipTypes, struct FST_ShipCustomisations_renamed>* Saved_Ship_Customizations);
	void Set_Player_Customization(const struct FST_PlayerCustomisation_renamed& Player_Customization);
	void Get_Player_Customization(struct FST_PlayerCustomisation_renamed* Player_Customization);
	void Set_Sort_Settings(const struct FST_NewSortOptions_renamed& Sort_Settings);
	void Get_Sort_Settings(struct FST_NewSortOptions_renamed* Sort_Settings);
	void Set_ServerHost_Settings(const struct FST_ServerHostSettings_renamed_2& Server_Host_Settings_renamed);
	void Get_ServerHost_Settings(struct FST_ServerHostSettings_renamed_2* Server_Host_Settings_renamed);
	void Set_GunGame_Host_Settings(const struct FST_GunGameHostSettings_renamed_2& GunGame_Host_Settings_new);
	void Get_GunGame_Host_Settings(struct FST_GunGameHostSettings_renamed_2* GunGame_Host_Settings_Renamed);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SG_SaveGame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SG_SaveGame_C")
	}
	static class USG_SaveGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USG_SaveGame_C>();
	}
};
DUMPER7_ASSERTS_USG_SaveGame_C;

SDK_NAMESPACE_END
