#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sound_Volume_Detecter

#include "Basic.hpp"

#include "Sound_Volume_Detecter_classes.hpp"
#include "Sound_Volume_Detecter_parameters.hpp"


SDK_NAMESPACE_START

// Function Sound_Volume_Detecter.Sound_Volume_Detecter_C.ExecuteUbergraph_Sound_Volume_Detecter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASound_Volume_Detecter_C::ExecuteUbergraph_Sound_Volume_Detecter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sound_Volume_Detecter_C", "ExecuteUbergraph_Sound_Volume_Detecter");

	Params::Sound_Volume_Detecter_C_ExecuteUbergraph_Sound_Volume_Detecter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sound_Volume_Detecter.Sound_Volume_Detecter_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASound_Volume_Detecter_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sound_Volume_Detecter_C", "ReceiveTick");

	Params::Sound_Volume_Detecter_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sound_Volume_Detecter.Sound_Volume_Detecter_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASound_Volume_Detecter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sound_Volume_Detecter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
