#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_Achievement_renamed

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_Achievement_renamed.ST_Achievement_renamed
// 0x000C (0x000C - 0x0000)
struct FST_Achievement_renamed final
{
public:
	int32                                         AchievementId_2_DA988AE0463ED60D1758D8829BDC934E;  // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   AchievementAPIname_8_C8B9006745E05A5AA05868917DCFAE17; // 0x0004(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_Achievement_renamed;

SDK_NAMESPACE_END
