#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_Customisation_renamed

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "E_ShipTypes_structs.hpp"
#include "E_CharacterFigure_structs.hpp"
#include "E_BodyTypes_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_Customisation_renamed.ST_Customisation_renamed
// 0x00F0 (0x00F0 - 0x0000)
struct FST_Customisation_renamed final
{
public:
	struct FLinearColor                           TestColor_3_246B648147329FED4847AFAEE444FFD3;      // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SpecialFlag_140_3598D7E34AF1707A7B5C74A16FC7D5F9;  // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Hat_11_1599CC2E4AD16BED0B93018280B1C8D4;           // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ShipSailColor_18_8C5372F643CD7BE1F1B61197EC01E98F; // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BowHead_17_58B4123C48A58809B133739280548F05;       // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SailEmblem_63_0D946D2349D189E2A5F136B6890A6C5E;    // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ShipHullColorSet_29_832EDDC049A2563C7A8008B9F328C88C; // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         FlagColorSet_33_0C0AD4A1412C0B4D0F35D9A46EAFDF13;  // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RopeColor_36_6A44F6D84B65D7CB8884CC93513DF7D4;     // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   ShipName_39_C746DA084E10CD3FDF1C4C859B240401;      // 0x0030(0x0018)(Edit, BlueprintVisible)
	int32                                         FlagEmblem_42_4FE4539A4210800631A88AB535B3BB36;    // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SkinColor_45_7C335432453D7FD00277EBACA53812E3;     // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Torso_85_928BE3324DE40FB0DA6128A34E22EA52;         // 0x0050(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Pants_51_DC68605B446257D8DE24D3BDCCF67578;         // 0x0054(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Beard_54_2F225F984E71218B319D4D9EE189613E;         // 0x0058(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LampColor_61_B512A5444920D0C2022AC484D81ACFC3;     // 0x005C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SailEmblemBottom_71_83303D6248EF41170568E69ADD7CDC99; // 0x0060(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SailColorBottom_72_593CED7E48E2B8F53F6DC4AE505C8F5C; // 0x0064(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ShipPaint_75_CEA3DD924B038F67E5F74ABE55426EEE;     // 0x0068(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VoicePitch_78_3254E7E743E24AEDB5E81DA92C7B0877;    // 0x006C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LeftFoot_115_BB0F0ED94A5FA1E468203D9318D4A67A;     // 0x0070(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         HairColor_84_C4E6D5384EC8821BBAA69586B80DD289;     // 0x0074(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         PegLeg_88_8D8FA4D04755C987BAAEE7BF72253C53;        // 0x0078(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PeglegLeft_90_DA6A71AE49E7988352A7D68BEB0015D5;    // 0x007C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          PirateCurse_176_0566C7DF4BBAE50C34210BAC58CD9EC7;  // 0x007D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          TorsoPiece2Enabled_97_C8CE2AA44FB9BB115D0EB8BCC181A9C9; // 0x007E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          TorsoPiece3Enabled_96_137BE77A4938BE977A101D8B8B5276EC; // 0x007F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          TorsoPiece4Enabled_98_5633C5E846828869680851BBCD1CB8C0; // 0x0080(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Tattoo_103_E284F086450B6E10B61D6F8ED79D12CB;       // 0x0084(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_BodyTypes                                   BodyType_106_8A4A7A9F4ECC6487FD6223BD4F700738;     // 0x0088(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           TattooColor_110_46CF04294D70A524EC2A3A9314C3495E;  // 0x008C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ShipPaintColor_114_2FD668AB4CD6C4C273C9F6A8D2DEF4C8; // 0x009C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RightFoot_118_E3E4767F4926DB58A36A369539AA0CB7;    // 0x00A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BowFigureColorSet1_124_A608FBC64E1984C4739BFF9CDBD58919; // 0x00A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BowFigureColorSet2_127_D2D37795461FF304131D8DA705122465; // 0x00A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BowFigureColorSet3_129_81CEA1E44B91445DFA6D04876E44E37F; // 0x00AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HullPaintDamageAmount_132_FF02D48F497DFB60C7A00A8C28DDF8FE; // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_ShipTypes                                   SelectedShipType_135_3F6EC6E4406E11AD5E1730B0C033979B; // 0x00B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B5[0x3];                                       // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         VoiceType_138_00AFC2744E8B59DB8D8727A119E5FE07;    // 0x00B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_CharacterFigure                             CharacterFigure_143_D68A585341C22268A8CA99A24A542B5C; // 0x00BC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         FaceItem_154_14A95CFE4A098FBC43B669BFD5417B86;     // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LeftHand_155_C120A2A24C55425478E2E98BCE599AC1;     // 0x00C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RightHand_156_768345D84E0706420C9C369829A64988;    // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Scar_157_E27FE4554F67648579BE53B3AB78B418;         // 0x00CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         HammerSkin_158_FDA8E5584ECDDD6DC65C168D917A818B;   // 0x00D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         FlagSetup_162_1F282424448727C71FBAB4A238FAB50B;    // 0x00D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LowerFaceItem_165_BC2CE43848613650347B209BC5A4E4AE; // 0x00D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SailTearAmount_168_10048221477C12B9AB93E88273FD493E; // 0x00DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SailPaintWear_170_EF1EFFE74C818EF14DA2F8847BDD2C2F; // 0x00E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SailDirtAmount_172_7F81415B4148D4188629889CFED65A90; // 0x00E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Title_175_9AC3336E4FE784033FADEC875439116C;        // 0x00E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurseBurden_179_F1D313594790ED77DA57639E56443C3F;  // 0x00EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_Customisation_renamed;

SDK_NAMESPACE_END
