#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_CullComponents_renamed

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_CullComponents_renamed.ST_CullComponents_renamed
// 0x0040 (0x0040 - 0x0000)
struct FST_CullComponents_renamed final
{
public:
	class UActorComponent*                        ComponentRef_2_CE7D1E5443F46DADF3ABD29490C0984C;   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECollisionEnabled                             CollisionSetting_5_552669FA43BA66978B629DB8D7DD2659; // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             RelativeTrasnform_8_17DA253349C66ED1945A9A85D1F33FE6; // 0x0010(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_FST_CullComponents_renamed;

SDK_NAMESPACE_END
