#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_Hint_renamed

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_Hint_renamed.ST_Hint_renamed
// 0x0018 (0x0018 - 0x0000)
struct FST_Hint_renamed final
{
public:
	class FText                                   HintText_2_4AC661D541DE951E2BD90996B5BCAB99;       // 0x0000(0x0018)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FST_Hint_renamed;

SDK_NAMESPACE_END
