#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteeringWheel_ABP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass SteeringWheel_ABP.SteeringWheel_ABP_C
// 0x0090 (0x0350 - 0x02C0)
class USteeringWheel_ABP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x02F8(0x0050)()
	float                                         CurrentFrame;                                      // 0x0348(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SteeringWheel_ABP(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SteeringWheel_ABP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SteeringWheel_ABP_C")
	}
	static class USteeringWheel_ABP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteeringWheel_ABP_C>();
	}
};
DUMPER7_ASSERTS_USteeringWheel_ABP_C;

SDK_NAMESPACE_END
