#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TODManager

#include "Basic.hpp"

#include "TODManager_classes.hpp"
#include "TODManager_parameters.hpp"


SDK_NAMESPACE_START

// Function TODManager.TODManager_C.ExecuteUbergraph_TODManager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTODManager_C::ExecuteUbergraph_TODManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TODManager_C", "ExecuteUbergraph_TODManager");

	Params::TODManager_C_ExecuteUbergraph_TODManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TODManager.TODManager_C.Set Time Of Day
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// E_TimesOfDay                            Time_of_Day_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTODManager_C::Set_Time_Of_Day(E_TimesOfDay Time_of_Day_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TODManager_C", "Set Time Of Day");

	Params::TODManager_C_Set_Time_Of_Day Parms{};

	Parms.Time_of_Day_0 = Time_of_Day_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TODManager.TODManager_C.Update TOD Elements
// (BlueprintCallable, BlueprintEvent)

void UTODManager_C::Update_TOD_Elements()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TODManager_C", "Update TOD Elements");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TODManager.TODManager_C.OnRep_Time Of Day
// (BlueprintCallable, BlueprintEvent)

void UTODManager_C::OnRep_Time_Of_Day()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TODManager_C", "OnRep_Time Of Day");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TODManager.TODManager_C.TOD_ChanceCalc
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Random_TOD_Index                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTODManager_C::TOD_ChanceCalc(int32* Random_TOD_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TODManager_C", "TOD_ChanceCalc");

	Params::TODManager_C_TOD_ChanceCalc Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Random_TOD_Index != nullptr)
		*Random_TOD_Index = Parms.Random_TOD_Index;
}


SDK_NAMESPACE_END
