#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BoatMarker_Galleon

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_BoatMarker_Galleon.UI_BoatMarker_Galleon_C
// 0x0008 (0x0268 - 0x0260)
class UUI_BoatMarker_Galleon_C final : public UUserWidget
{
public:
	class UImage*                                 Image_89;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_BoatMarker_Galleon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_BoatMarker_Galleon_C")
	}
	static class UUI_BoatMarker_Galleon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_BoatMarker_Galleon_C>();
	}
};
DUMPER7_ASSERTS_UUI_BoatMarker_Galleon_C;

SDK_NAMESPACE_END
