#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ConquestFlag

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UI_DirectionIndicatorImageBase_classes.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_ConquestFlag.UI_ConquestFlag_C
// 0x0170 (0x03E8 - 0x0278)
class UUI_ConquestFlag_C final : public UUI_DirectionIndicatorImageBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_ConquestFlag_C;                  // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           CanvasPanel_0;                                     // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_2;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_3;                                     // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel_5;                                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Arrow;                                       // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Flag;                                        // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_76;                                    // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           RedBar;                                            // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ABP_ConquestFlag_C*                     FlagRef;                                           // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Distant;                                           // 0x02C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            IconBrush;                                         // 0x02D0(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            ArrowBrush;                                        // 0x0358(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          HideFlagIcon;                                      // 0x03E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          HideArrow;                                         // 0x03E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_ConquestFlag(int32 EntryPoint);
	void SetAngle(float Degrees);
	void InitializeIconOnly(class UObject* Icon);
	void SetScale(const struct FVector2D& S);
	void Initialize(class UObject* Icon, class UObject* Arrow);
	struct FLinearColor SetIconColor();
	float SetCaptureProgress();
	struct FLinearColor SetProgressBarColor();
	ESlateVisibility Get_RedBar_Visibility_0();
	ESlateVisibility Get_BlueBar_Visibility_0();
	float Get_BlueBar_Percent_0();
	ESlateVisibility ShowFlagIcon();
	ESlateVisibility ShowFullFlagIcon();
	ESlateVisibility ShowFullWidget();
	ESlateVisibility Get_Image_Arrow_Visibility_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_ConquestFlag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_ConquestFlag_C")
	}
	static class UUI_ConquestFlag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ConquestFlag_C>();
	}
};
DUMPER7_ASSERTS_UUI_ConquestFlag_C;

SDK_NAMESPACE_END
