#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Commands

#include "Basic.hpp"

#include "UI_Commands_classes.hpp"
#include "UI_Commands_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_Commands.UI_Commands_C.ExecuteUbergraph_UI_Commands
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Commands_C::ExecuteUbergraph_UI_Commands(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Commands_C", "ExecuteUbergraph_UI_Commands");

	Params::UI_Commands_C_ExecuteUbergraph_UI_Commands Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Commands.UI_Commands_C.BndEvt__ComboBox_Group_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FString&                    SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Commands_C::BndEvt__ComboBox_Group_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Commands_C", "BndEvt__ComboBox_Group_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature");

	Params::UI_Commands_C_BndEvt__ComboBox_Group_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Commands.UI_Commands_C.Destroy
// (BlueprintCallable, BlueprintEvent)

void UUI_Commands_C::Destroy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Commands_C", "Destroy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Commands.UI_Commands_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Commands_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Commands_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Commands.UI_Commands_C.CreateButtons
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void()>&                OnExecuteCommand                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
// TArray<class FName>&                    Commands                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Commands_C::CreateButtons(const TDelegate<void()>& OnExecuteCommand, TArray<class FName>& Commands)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Commands_C", "CreateButtons");

	Params::UI_Commands_C_CreateButtons Parms{};

	Parms.OnExecuteCommand = OnExecuteCommand;
	Parms.Commands = std::move(Commands);

	UObject::ProcessEvent(Func, &Parms);

	Commands = std::move(Parms.Commands);
}


SDK_NAMESPACE_END
