#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Character

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_CharacterMenus_structs.hpp"
#include "UI_MainCustomizationMenuBase_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_Character.UI_Character_C
// 0x0148 (0x03B8 - 0x0270)
class UUI_Character_C final : public UUI_MainCustomizationMenuBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UButton*                                Button_2;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_4;                                          // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_148;                                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_191;                                         // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_220;                                         // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_221;                                         // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_222;                                         // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_753;                                         // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         Percentage_Unlocked;                               // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_0;                                     // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x02C8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BodySettings_C*                     UI_BodySettings;                                   // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton;                                 // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_0;                             // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_1;                             // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_2;                             // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_3;                             // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_4;                             // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_5;                             // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_6;                             // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_7;                             // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_8;                             // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_9;                             // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_10;                            // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_11;                            // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_12;                            // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_13;                            // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_14;                            // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CategoryButton_C*                   UI_CategoryButton_C_15;                            // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Character_Clothing_C*               UI_Character_Clothing;                             // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_HammerAndBurdensSkinsList_C*        UI_HammerSkinsList;                                // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Presets_C*                          UI_SavedOutfits;                                   // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_TitleList_C*                        UI_TitleList;                                      // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ABP_Mannequin_C*                        MannequinRef;                                      // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MannequinFaceMaterialInstance;                     // 0x0388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         FaceIndex;                                         // 0x0390(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         HatIndex;                                          // 0x0394(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MannequinHatMaterialInstance;                      // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_CharacterMenus                              ActiveCharacterMenu;                               // 0x03A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A1[0x3];                                      // 0x03A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PantsIndex;                                        // 0x03A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BeltIndex;                                         // 0x03A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BeardIndex;                                        // 0x03AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FetchPlayerData;                                   // 0x03B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_Character(int32 EntryPoint);
	void Loading_Inventory_Complete();
	void LoadHats();
	void BndEvt__UI_CategoryButton_C_15_K2Node_ComponentBoundEvent_3_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_14_K2Node_ComponentBoundEvent_2_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_13_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_8_K2Node_ComponentBoundEvent_0_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_12_K2Node_ComponentBoundEvent_30_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_11_K2Node_ComponentBoundEvent_29_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_10_K2Node_ComponentBoundEvent_28_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_9_K2Node_ComponentBoundEvent_27_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_7_K2Node_ComponentBoundEvent_26_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_6_K2Node_ComponentBoundEvent_25_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_5_K2Node_ComponentBoundEvent_24_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_4_K2Node_ComponentBoundEvent_23_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_3_K2Node_ComponentBoundEvent_22_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_2_K2Node_ComponentBoundEvent_21_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_1_K2Node_ComponentBoundEvent_20_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_C_0_K2Node_ComponentBoundEvent_17_OnPressed__DelegateSignature();
	void BndEvt__UI_CategoryButton_K2Node_ComponentBoundEvent_14_OnPressed__DelegateSignature();
	void BndEvt__Button_4_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void RefreshCharacterUI();
	void BndEvt__Button_2_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void LoadCustomisation();
	void NextCosmetic(int32 Index_0, class UDataTable* DataTable, int32* NewIndex);
	void PreviousCosmetic(int32 Index_0, class UDataTable* DataTable, int32* NewIndex);
	void LoadActiveTab();
	float SetUnlockProcent();
	class FText SetUnlockProcentText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Character_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Character_C")
	}
	static class UUI_Character_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Character_C>();
	}
};
DUMPER7_ASSERTS_UUI_Character_C;

SDK_NAMESPACE_END
