#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Compass

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_Compass.UI_Compass_C
// 0x0038 (0x0298 - 0x0260)
class UUI_Compass_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_164;                                         // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_325;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Compass;                                       // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CompassMatRef;                                     // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FLinearColor>                   Colors;                                            // 0x0288(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_UI_Compass(int32 EntryPoint);
	void PlayerRespawned(int32 Team_ID, int32 Player_ID);
	void PlayerDied(int32 Team_ID, int32 Player_ID);
	void MarkerRemoved(int32 Team_ID, int32 Player_ID);
	void MarkerPlaced(int32 Team_ID, int32 Player_ID, const struct FVector& Location);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void SetMarker(int32 Player_ID, const struct FVector& Location);
	void RemoveMarker(int32 Player_ID);
	void UpdateShipLocation();
	void UpdatePlayerLocations();
	void SetPlayerMarker(int32 Player_ID, const struct FVector& Location);
	void SetPlayerDeathIcon(int32 Player_ID);
	void SetPlayerAliveIcon(int32 Player_ID);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Compass_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Compass_C")
	}
	static class UUI_Compass_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Compass_C>();
	}
};
DUMPER7_ASSERTS_UUI_Compass_C;

SDK_NAMESPACE_END
