#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CannonAmmo

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_CannonAmmo.UI_CannonAmmo_C.ExecuteUbergraph_UI_CannonAmmo
// 0x0044 (0x0044 - 0x0000)
struct UI_CannonAmmo_C_ExecuteUbergraph_UI_CannonAmmo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_ExecuteUbergraph_UI_CannonAmmo;

// Function UI_CannonAmmo.UI_CannonAmmo_C.Tick
// 0x003C (0x003C - 0x0000)
struct UI_CannonAmmo_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_Tick;

// Function UI_CannonAmmo.UI_CannonAmmo_C.Set_Img
// 0x0008 (0x0008 - 0x0000)
struct UI_CannonAmmo_C_Set_Img final
{
public:
	class UTexture2D*                             Image;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_Set_Img;

// Function UI_CannonAmmo.UI_CannonAmmo_C.Set_CannonballAmount
// 0x0070 (0x0070 - 0x0000)
struct UI_CannonAmmo_C_Set_CannonballAmount final
{
public:
	int32                                         Amount;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0008(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0048(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0058(0x0018)()
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_Set_CannonballAmount;

// Function UI_CannonAmmo.UI_CannonAmmo_C.Select
// 0x0001 (0x0001 - 0x0000)
struct UI_CannonAmmo_C_Select final
{
public:
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_Select;

// Function UI_CannonAmmo.UI_CannonAmmo_C.GetVisibility_0
// 0x0002 (0x0002 - 0x0000)
struct UI_CannonAmmo_C_GetVisibility_0 final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_GetVisibility_0;

// Function UI_CannonAmmo.UI_CannonAmmo_C.GetEnabledColor
// 0x0010 (0x0010 - 0x0000)
struct UI_CannonAmmo_C_GetEnabledColor final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_GetEnabledColor;

// Function UI_CannonAmmo.UI_CannonAmmo_C.SetActionbarIndex
// 0x0020 (0x0020 - 0x0000)
struct UI_CannonAmmo_C_SetActionbarIndex final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0018)()
};
DUMPER7_ASSERTS_UI_CannonAmmo_C_SetActionbarIndex;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
