#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ConquestFlagSwap

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UI_ConquestFlagSwap.UI_ConquestFlagSwap_C.ExecuteUbergraph_UI_ConquestFlagSwap
// 0x0010 (0x0010 - 0x0000)
struct UI_ConquestFlagSwap_C_ExecuteUbergraph_UI_ConquestFlagSwap final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UI_ConquestFlagSwap_C_ExecuteUbergraph_UI_ConquestFlagSwap;

// Function UI_ConquestFlagSwap.UI_ConquestFlagSwap_C.SetNewFlagName
// 0x0030 (0x0030 - 0x0000)
struct UI_ConquestFlagSwap_C_SetNewFlagName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_GameState_C*                        K2Node_DynamicCast_AsBP_Game_State;                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UI_ConquestFlagSwap_C_SetNewFlagName;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
